// GENERATED extract from sabias_que_service — Spanish daily tips (730).
// ignore_for_file: lines_longer_than_80_chars

const List<String> kSabiasQueTipsEs = [
'El contacto piel con piel ayuda a estabilizar el ritmo cardíaco del recién nacido.',
'No uses toallitas con alcohol; agua y jabón neutro o toallitas de agua son lo mejor.',
'El meconio (primera caca) es pegajoso; aplica un poco de aceite de bebé para limpiarlo mejor.',
'Tu bebé no tiene horario; la lactancia (materna o fórmula) debe ser a demanda.',
'El cordón umbilical suele caer entre los 5 y 15 días; mantenlo seco.',
'Si llora mucho, el ruido blanco (secador, campana extractora) puede calmarlo.',
'Los bebés nacen con la vista borrosa; solo ven bien a 25 cm de distancia.',
'No te preocupes por sus manos y pies fríos; su sistema circulatorio aún está madurando.',
'El hipo es muy común y no les hace daño; no intentes quitárselo con sustos.',
'La "crisis de los 15 días" es real: querrá comer mucho más para aumentar la producción.',
'Los bebés no necesitan almohada; su cuello debe estar plano para respirar bien.',
'Si tiene gases, encoge sus piernas hacia su pecho suavemente (efecto "bicicleta").',
'El baño no tiene por qué ser diario; 3 veces por semana es suficiente al principio.',
'No le cortes las uñas aún; son muy blandas y están pegadas a la piel. Usa limas de cartón.',
'Es normal que pierda peso los primeros días; lo recuperará en la segunda semana.',
'La vitamina D es esencial: dásela todos los días según te indique el pediatra.',
'No tapes al bebé en exceso; si su nuca está sudada, le sobra ropa.',
'Tu bebé reconoce tu voz desde el útero; háblale mucho, aunque no te responda.',
'Los estornudos son su forma de limpiar la nariz de polvo o pelusas; no es un resfriado.',
'El reflejo de prensión (te agarra el dedo) es instintivo y muy fuerte.',
'Si toma pecho, tu alimentación debe ser variada; no hay alimentos prohibidos (salvo alcohol).',
'Las cacas de un bebé de pecho suelen ser líquidas y con grumos; es normal.',
'Duerme cuando el bebé duerma; el cansancio acumulado es el peor enemigo del padre.',
'El instinto de succión les calma; a veces solo quieren succionar aunque no tengan hambre.',
'No uses suavizante en su ropa; puede irritar su piel extremadamente sensible.',
'El acné del lactante son granitos por tus hormonas; no los toques, desaparecen solos.',
'Si el bebé está irritable, un paseo al aire libre suele ser "mano de santo".',
'No permitas que besen al bebé en la cara o manos para evitar contagios de virus.',
'El reflejo de marcha: si lo sostienes de pie, moverá las piernas como si caminara.',
'Los cólicos suelen aparecer al final del día; mantén la calma, tú eres su refugio.',
'Alrededor de las 6 semanas llega la primera "sonrisa social"; ¡disfrútala!',
'Empieza a emitir sonidos guturales como "ajó"; imítalo para fomentar su lenguaje.',
'El "tummy time" (tiempo boca abajo) ayuda a fortalecer su cuello; hazlo 2 min varias veces.',
'Sus ojos pueden cruzarse a veces (estrabismo funcional); es normal hasta los 4 meses.',
'Empieza a seguir objetos con la mirada; usa juguetes de colores contrastados.',
'Ya puedes cortarle las uñas con tijeras de punta redonda mientras duerme.',
'Si usa chupete, espera a que la lactancia esté establecida para introducirlo.',
'Las manos ya no están siempre en puño; empieza a abrirlas y explorarlas.',
'La costra láctea en la cabeza no pica; se quita poco a poco con aceite y cepillado suave.',
'Si llora sin consuelo, comprueba que no tenga un hilo o pelo enrollado en un dedo del pie.',
'Es el mes de las primeras vacunas; ten paracetamol infantil a mano por si le da fiebre.',
'Notarás que babea más; está descubriendo sus glándulas salivales.',
'Empieza a distinguir los colores primarios, especialmente el rojo.',
'Ponle música suave; ayuda a su desarrollo cognitivo y auditivo.',
'Los masajes antes del baño reducen el estrés del bebé y de sus papás.',
'No lo fuerces a sentarse; su columna aún no tiene la fuerza necesaria.',
'Si regurgita un poco de leche después de comer, es normal mientras gane peso.',
'Empieza a mostrar preferencia por las caras humanas frente a los objetos.',
'El llanto nocturno puede ser por sobreestimulación durante el día.',
'Deja que experimente con diferentes texturas de ropa (algodón, lana suave).',
'Los móviles de cuna deben estar a una distancia donde no pueda alcanzarlos.',
'Si se queda dormido en el coche, pásalo a su cuna en cuanto llegues a casa.',
'Fomenta el contacto visual mientras le cambias el pañal; es un momento de conexión.',
'Empieza a reconocer la rutina: baño -> pijama -> cena -> dormir.',
'Es normal que pase varios días sin hacer caca si toma solo pecho; no es estreñimiento.',
'El porteo ergonómico es ideal para tener las manos libres y al bebé calmado.',
'No uses andadores; son peligrosos y perjudiciales para su desarrollo motor.',
'Evita perfumes fuertes cerca del bebé; su olfato es muy sensible.',
'Empieza a patalear con fuerza; asegúrate de que el pañal no le apriete el abdomen.',
'Tu bebé ya sabe quién es su figura principal de apego.',
'Boca abajo ya intenta levantar la cabeza y el pecho; fortalece el cuello, base de futuros movimientos.',
'Empieza a descubrir sus manos: las mira, las chupa y las junta en el centro del cuerpo.',
'La coordinación mano-ojo mejora; intenta alcanzar juguetes aunque a veces falle el tiro.',
'Si le hablas desde un lado de la habitación, ya debería girar la cabeza para buscarte.',
'Los balbuceos son más complejos: añade sonidos como "p", "b" y "m".',
'Es buen momento para introducir un gimnasio de actividades en el suelo.',
'Ya distingue mejor los matices de color; los juguetes brillantes le fascinan.',
'El sueño empieza a consolidarse un poco más por la noche, aunque cada bebé es un mundo.',
'Notarás que tiene más fuerza en las piernas y patalea con mucha energía.',
'Si tiene mucha saliva, puede ser por la maduración de las glándulas, no necesariamente dientes.',
'El contacto social le encanta; sonríe a casi cualquier persona que le haga mimos.',
'Empieza a imitar tus expresiones faciales; sácale la lengua y verás si lo intenta.',
'Los libros de tela con diferentes texturas son ideales para sus manos curiosas.',
'Evita dejarlo en la hamaca muchas horas; el suelo es donde más aprende.',
'Si toma biberón, comprueba que la tetina tiene el flujo adecuado para su edad.',
'La "angustia del octavo día" ya pasó; ahora entra en una fase más estable.',
'El llanto ahora tiene "intención": llora distinto si tiene hambre o si está aburrido.',
'Es normal que empiece a llevarse todo a la boca; es su forma de conocer el mundo.',
'Dale masajes en las piernas para relajarlo después de un día de mucho pataleo.',
'Si usas chupete, revisa que no esté gastado o tenga grietas.',
'Ya puede sostener un sonajero durante unos segundos antes de soltarlo.',
'Notarás que el bebé se "estira" y pierde esa postura fetal del principio.',
'Hablarle sobre lo que estás haciendo ("Ahora papá te va a cambiar el pañal") ayuda a su cerebro.',
'Los paseos en el cochecito son mejores si puede ver un poco más de paisaje (sube un punto el respaldo).',
'Si todavía tiene reflejo de Moro muy fuerte, el arrullo suave puede ayudarle a dormir.',
'El color de ojos puede empezar a cambiar hacia su tono definitivo ahora.',
'Empieza a reír a carcajadas; los ruidos divertidos de papá son su mejor comedia.',
'No uses zapatos rígidos; los pies necesitan libertad total para desarrollarse.',
'El baño puede pasar de ser un trámite a ser un momento de juego con salpicaduras.',
'Aprovecha para hacerle fotos de perfil; su cara cambia muy rápido en este mes.',
'Alrededor de esta edad puede empezar la "regresión del sueño de los 4 meses"; es un cambio madurativo, ten paciencia.',
'El cerebro del bebé empieza a procesar el sueño como el de un adulto (fases REM y profundas).',
'Ya puede girar de la espalda al lado; nunca lo dejes solo en el cambiador.',
'Su visión es casi como la de un adulto en términos de enfoque y color.',
'Se fija en los objetos pequeños; cuidado con piezas que puedan caer al suelo.',
'Si lo sostienes por las axilas, ya apoya peso en sus pies y "brinca".',
'Empieza a reconocer su nombre; se girará cuando lo llames.',
'El interés por la comida de los adultos empieza; te mirará fijamente mientras comes.',
'Sus periodos de vigilia (despierto) son más largos, de aproximadamente 1.5 a 2 horas.',
'Los juegos de "cu-cu tras" (taparse la cara) empiezan a tener sentido para él.',
'No introduzcas sólidos aún; la OMS recomienda esperar a los 6 meses.',
'Si babea mucho y está irritable, los mordedores fríos serán tus mejores aliados.',
'Puede empezar a agarrar sus propios pies mientras está boca arriba.',
'El llanto por aburrimiento aparece; necesita estímulos nuevos cada poco tiempo.',
'Se acercan las vacunas de los 4 meses; pregunta al pediatra la fecha exacta y ten paracetamol infantil a mano si te lo indica.',
'Si notas una zona roja en su encía, es que un diente está empujando.',
'Los juguetes con luces y sonidos sencillos le ayudan a entender causa-efecto.',
'Empieza a pasar objetos de una mano a la otra.',
'Su espalda es más fuerte; si lo sientas con apoyo, se mantiene un rato.',
'El sueño diurno suele estabilizarse en 3 o 4 siestas claras.',
'No uses pantallas (móvil, TV) para distraerlo; su cerebro no las procesa bien.',
'Cámbiale el juguete de mano para fomentar la lateralidad.',
'Si hace mucho calor, puedes ofrecerle el pecho o biberón con más frecuencia, pero no agua.',
'Escuchar diferentes idiomas (canciones) a esta edad es excelente para su plasticidad cerebral.',
'El reflejo de extrusión (sacar la lengua) sigue presente, por eso no debe comer sólidos aún.',
'Empieza a "gritar" de alegría; está probando la potencia de sus pulmones.',
'Si lo bañas por la noche, usa poca luz para que asocie el baño con dormir.',
'Notarás que se distrae fácilmente mientras come porque todo le interesa.',
'Ponle frente a un espejo seguro; le fascinará el "otro bebé" que ve.',
'Es un mes de muchos cambios; si estás agotado, pide relevo. También vosotros necesitais descanso.',
'Ya puede rodar sobre sí mismo (de boca arriba a boca abajo). ¡Objetivo cumplido!',
'Es capaz de distinguir entre caras conocidas y extraños; puede empezar a ser selectivo.',
'Su fuerza de agarre es sorprendente; cuidado con tu pelo o tus gafas.',
'Empieza a sentarse con muy poco apoyo, usando sus manos como "trípode".',
'La curiosidad es máxima; querrá tocar todo lo que tú toques.',
'Si le quitas un juguete, protestará; empieza a entender la posesión.',
'Los sonidos de pedorretas con la boca le hacen muchísima gracia.',
'Puede empezar a desplazarse "reptando" o girando como las agujas de un reloj.',
'El peso del bebé suele haberse duplicado desde el nacimiento.',
'Si le ofreces un juguete, ya extiende los brazos para cogerlo con intención clara.',
'Sus manos están abiertas casi todo el tiempo, listas para la acción.',
'Ya puede sostener su propio biberón si toma fórmula (aunque siempre con supervisión).',
'Empieza a entender el tono de tu voz: distingue si estás alegre o si le riñes suavemente.',
'Los juegos en la alfombra son su actividad principal; asegúrate de que esté limpia.',
'Es un buen momento para leer cuentos con sonidos de animales.',
'Si llora por la noche, intenta calmarlo con tu voz antes de cogerlo, para que aprenda a autorregularse.',
'Notarás que el bebé se mira los pies con curiosidad, como si no fueran suyos.',
'Su sistema digestivo se prepara poco a poco; la alimentación complementaria llega hacia los 6 meses cumplidos.',
'El babeo puede causar irritación en la barbilla; aplica un poco de bálsamo protector.',
'Empieza a "conversar" contigo esperando a que tú dejes de hablar para emitir su sonido.',
'Los juguetes de caucho natural son los mejores para morder ahora.',
'No lo dejes en el parque (corralito) demasiado tiempo; necesita explorar el espacio real.',
'Sigue sin introducir sólidos: la OMS recomienda esperar a los 6 meses cumplidos.',
'La ropa ya debe ser cómoda y elástica para no frenar sus movimientos de giro.',
'Es normal que dé patadas en el agua del baño hasta ponerlo todo perdido.',
'Empieza a seguir objetos que caen al suelo con la mirada.',
'Si tiene hermanos mayores, este es el mes donde más empieza a interactuar con ellos.',
'La siesta de la tarde puede empezar a acortarse.',
'Mantén los productos de limpieza y cables fuera de su alcance desde ya; pronto llegará a ellos.',
'Practica el sentarlo con apoyo unos minutos al día; necesita un buen control de tronco antes de comer.',
'Muchos bebés empiezan a pivotar o "reptar" boca abajo; aún no es gateo, pero ya se desplazan un poco.',
'El balbuceo gana fuerza: oirás sílabas sueltas como "ba", "ma" o "da".',
'Ofrece mordedores seguros: alivia las encías y fortalece manos y boca.',
'Si le quitas un juguete, protestará con más claridad; está aprendiendo a expresar lo que quiere.',
'Los libros de tela o cartón grueso con texturas son ideales para explorar con las manos.',
'Los juguetes de causa-efecto (apretar y que suene) le ayudan a entender que sus acciones tienen resultado.',
'No compares su progreso con el de otros bebés; el desarrollo motor es muy individual.',
'Practica el tummy time varios ratos al día: fortalece cuello, espalda y brazos.',
'Empieza a sentarse con apoyo (cojines o tu cuerpo); no lo dejes sentado solo sin supervisión.',
'Tirar un juguete al suelo y que tú lo recojas le enseña gravedad... y paciencia a los papás.',
'El sueño puede volverse irregular si está practicando volteretas o a sentarse.',
'La leche (materna o fórmula) sigue siendo su único alimento; aún no necesita yogur ni otros lácteos de vaca.',
'Con música moverá brazos y tronco con entusiasmo: es su forma de "bailar".',
'Como ya se mueve más, revisa la cuna: colchón firme, sin objetos sueltos ni almohadas.',
'Te mirará fijamente mientras comes; el interés por la comida suele aparecer semanas antes de probarla.',
'Falta poco para los 6 meses: infórmate sobre alimentación complementaria y cortes seguros (BLW o purés).',
'Babeo y encías sensibles son habituales; un masaje suave con tu dedo limpio puede aliviarlo.',
'Aún es pronto para el gateo en la mayoría; si solo rueda o pivota, va perfecto a su ritmo.',
'Con apoyo puede mantenerse sentado un rato e intentar jugar con las manos.',
'Pon un juguete un poco lejos en la alfombra: practicará girarse y alcanzarlo sin forzarlo a gatear.',
'Si tienes dudas sobre cuándo empezar con sólidos, pregunta al pediatra; la referencia habitual son 6 meses cumplidos.',
'Distingue cada vez mejor caras conocidas; puede ponerse serio o inquieto con personas nuevas.',
'Si lloriquea al dejarte en brazos de otra persona, es apego sano: despídete con calma y vuelve.',
'Sonajeros y objetos fáciles de agarrar siguen siendo excelentes para su coordinación mano-ojo.',
'Descalzo en casa siempre que puedas: necesita sentir superficies y mover los pies con libertad.',
'No adelantes la alimentación complementaria sin indicación médica; su digestivo aún está madurando.',
'Su agarre mejora: sujeta juguetes con más firmeza y los lleva a la boca para explorarlos.',
'Todo va a la boca: mantén fuera de alcance monedas, imanes, pilas y objetos pequeños.',
'Imita sus sonidos y gestos; es una de las mejores formas de fomentar el lenguaje ahora.',
'¡Felicidades! Estás a punto de llegar a la gran frontera de los 6 meses.',
'La OMS recomienda iniciar la alimentación complementaria ahora, manteniendo la leche como alimento principal.',
'Si optas por Baby Led Weaning (BLW), asegúrate de que los trozos sean blandos y alargados.',
'No añadas sal ni azúcar a sus comidas; sus riñones no están preparados y no los necesita.',
'¡Medio año de vida! Es un gran momento para una foto familiar de celebración.',
'Es normal que al principio solo juegue con la comida y apenas trague nada.',
'Muchos bebés ya se mantienen sentados con poco apoyo o solos; si aún necesita ayuda, practica con calma.',
'El agua se ofrece por primera vez junto con las comidas, mejor en vaso de aprendizaje.',
'La plancha o el huevo deben estar siempre muy bien cocinados para evitar riesgos.',
'Las cacas cambiarán de olor, color y consistencia radicalmente con la comida sólida.',
'Es el momento de comprar una trona segura y fácil de limpiar (vas a limpiar mucho).',
'Los cereales no tienen por qué ser de caja; el arroz, la avena o el maíz natural son mejores.',
'Dale su propia cuchara mientras tú le das con otra; le encanta imitar.',
'La miel está estrictamente prohibida antes del año por riesgo de botulismo.',
'El hierro es vital ahora; prioriza alimentos como legumbres, carne o cereales integrales.',
'No fuerces al bebé a comer; él sabe cuándo está saciado. Respeta sus señales.',
'El baño después de comer puede ser una buena estrategia para limpiar el desastre.',
'Empezará a pasar objetos de una mano a otra con total fluidez.',
'Sus siestas pueden empezar a ser más predecibles: una a media mañana y otra tras comer.',
'Ya puede distinguir tonos de voz: sabe perfectamente cuándo estás bromeando.',
'Juega a esconder objetos bajo una manta; empezará a buscarlos.',
'El babeo puede intensificarse si están por salir los primeros incisivos inferiores.',
'Si le das purés, intenta que no sean siempre una mezcla líquida; deja algún grumito.',
'El pescado blanco se puede introducir ahora; vigila siempre las espinas.',
'Es un buen momento para llevarlo a la compra; los colores del mercado le fascinan.',
'No uses pantallas para que coma; debe ser consciente de la comida y de su saciedad.',
'Si se atraganta un poco (arcada), mantén la calma; es su reflejo de seguridad actuando.',
'Los frutos secos enteros están prohibidos por riesgo de asfixia hasta los 5 años (pueden ir molidos).',
'Puede empezar a usar más el dedo índice para señalar o explorar detalles; aún es un inicio.',
'Notarás que ya tiene una "personalidad" muy marcada en sus gustos.',
'Un espejo a su altura en la zona de juegos le ayudará a reconocerse.',
'Puede aparecer la "angustia de separación": llora si te pierde de vista un segundo.',
'Este miedo es señal de inteligencia: ya sabe que eres único y que te puedes ir.',
'Juega mucho al "cucu-tras" para que entienda que aunque no te vea, siempre vuelves.',
'Empieza a hacer la "pinza" (coger cosas con el pulgar e índice).',
'Su curiosidad por los enchufes aumenta; es vital que estén protegidos.',
'Ya puede comer alimentos más picados o aplastados con el tenedor.',
'Le encanta imitar sonidos de animales; el perro y la vaca son los clásicos.',
'Si intenta ponerse de pie apoyado en los muebles, vigila que no se le caigan encima.',
'Las legumbres son excelentes para su dieta; dáselas bien cocidas y chafadas.',
'Su memoria a corto plazo mejora: recuerda dónde guardas sus juguetes.',
'Es normal que rechace alimentos que antes le gustaban; no desistas, vuelve a intentarlo.',
'La hora del baño puede ser más larga ahora que disfruta jugando con el agua.',
'Algunos bebés empiezan a señalar con el dedo lo que quieren; si aún no, llegará en los próximos meses.',
'No uses el móvil delante de él como distracción; prefiere tu interacción real.',
'Si gatea, asegúrate de que no haya monedas o piezas pequeñas en el suelo.',
'Empieza a entender el concepto de "dentro" y "fuera" (meter bloques en un cubo).',
'Su vocabulario receptivo (lo que entiende) es mucho mayor que el expresivo.',
'Las cenas deben ser ligeras para que no interfieran con su descanso nocturno.',
'Si tiene moquitos, el lavado nasal antes de dormir le ayudará a descansar mejor.',
'Deja que experimente con la cuchara aunque termine con comida en el pelo.',
'Ya puede beber pequeñas cantidades de agua de una botella o vaso normal con ayuda.',
'El reflejo de masticación está muy activo aunque no tenga muchos dientes.',
'Empieza a mostrar preferencias claras por ciertos juguetes o peluches.',
'Los juegos de "palmas palmitas" ayudan a su coordinación y ritmo.',
'Notarás que se gira inmediatamente cuando oye un sonido familiar fuera de la habitación.',
'Si duerme en su habitación, un vigilabebés te dará tranquilidad en esta etapa de movimiento.',
'Es un buen momento para empezar a establecer límites suaves ("eso no se toca").',
'Las manos siempre limpias; ahora que explora el suelo, el riesgo de virus aumenta.',
'El sol directo sigue siendo peligroso; busca siempre la sombra en los paseos.',
'Elogia sus logros; tu reacción positiva es su mayor motivación para aprender.',
'Muchos bebés ya se ponen de pie solos apoyándose en el sofá o en tus piernas.',
'Empezará a dar "pasos laterales" mientras se sujeta a los muebles (crucero).',
'Entiende perfectamente la palabra "No", aunque a veces decida ignorarla.',
'Le fascinan los libros con solapas que puede levantar él mismo.',
'Es capaz de sostener un objeto en cada mano y golpearlos entre sí para hacer ruido.',
'Su dieta ya es muy parecida a la de los adultos, solo que sin sal ni picantes.',
'Si gatea con rapidez, prepárate para perseguirlo por toda la casa.',
'Empieza a soltar objetos a propósito para ver cómo caen y qué ruido hacen.',
'La comunicación es más bidireccional; espera tu respuesta tras hacer un sonido.',
'Es capaz de encontrar un juguete que has escondido totalmente delante de él.',
'Las siestas pueden reducirse a dos muy claras y estables.',
'No le des alimentos con formas redondas pequeñas (uvas enteras, tomates cherry) sin cortar.',
'Su destreza con la pinza digital le permite coger hasta una miga de pan.',
'Empezará a intentar "ayudarte" cuando lo vistes, metiendo el brazo por la manga.',
'Los juegos de causa-efecto (apretar un botón y que suene algo) le obsesionan.',
'Notarás que el bebé tiene "apego" a un objeto específico (manta o peluche) para dormir.',
'Si balbucea mucho, intenta "traducirle": "¿Quieres el coche rojo?".',
'Es un buen momento para introducir rutinas de limpieza de dientes con un cepillo muy suave.',
'Cuidado con los manteles; si tira de ellos, lo que hay encima le caerá encima.',
'El gateo fortalece los músculos que usará más adelante para escribir y comer.',
'Empieza a reconocer canciones específicas y puede intentar hacer los gestos.',
'Si se cae (y se caerá), no entres en pánico; tu calma le ayuda a evaluar si duele de verdad.',
'Ya puede comer pasta de formas pequeñas o cortada para practicar el agarre.',
'Su curiosidad por la comida de tu plato es la mejor forma de que pruebe cosas nuevas.',
'El cambio de pañal se vuelve un reto porque no quiere estar quieto; ten un juguete a mano.',
'Empieza a entender conceptos espaciales como "arriba" y "abajo".',
'Su risa es contagiosa; los juegos de cosquillas suaves funcionan de maravilla.',
'Si sales a cenar, lleva juguetes que no hagan mucho ruido para mantenerlo entretenido.',
'La relación con otros niños se basa en la observación; les mira con muchísima atención.',
'¡Ya casi estamos en el año! Tu bebé ha crecido y aprendido más en estos 9 meses que en el resto de su vida.',
'Es muy probable que ya se desplace por toda la casa apoyándose en los muebles ("cruising").',
'Empieza a entender encargos sencillos ("coge el juguete"); las de dos pasos llegarán más adelante.',
'Le encanta meter y sacar cosas de cajas o cajones; es un ejercicio de lógica excelente.',
'Si ya se pone de pie, revisa que no haya objetos pesados en manteles que pueda tirar hacia abajo.',
'Su lenguaje gestual es clave: dirá "no" con la cabeza antes de saber decirlo con la boca.',
'Ya puede comer casi de todo, incluyendo legumbres enteras (bien cocidas) y trozos de carne tierna.',
'El juego del escondite (tú te escondes y él te busca) le genera muchísima risa y expectación.',
'Empieza a mostrar interés por usar el peine o el cepillo de dientes por sí mismo.',
'La curiosidad por los cables es máxima; usa canaletas para ocultar los de la TV o el router.',
'Puede empezar a tener "rabietas" de frustración cuando algo no le sale como quiere.',
'Es capaz de agacharse para recoger algo del suelo mientras se sujeta a un mueble.',
'Sus balbuceos empiezan a sonar a "conversación real" aunque no entiendas las palabras.',
'Los libros con sonidos reales (animales, coches) son su debilidad en este mes.',
'Si intenta subir escaleras, deja que lo haga siempre bajo tu supervisión para que aprenda.',
'Ya reconoce a los personajes de sus cuentos favoritos; señálalos y que los busque.',
'Empieza a imitar tareas del hogar: "limpiar" con un trapo o intentar barrer.',
'La siesta de la mañana puede empezar a ser más corta o desaparecer en algunos bebés.',
'No le des alimentos con riesgo de atragantamiento como palomitas o caramelos.',
'Fomenta su autonomía dejándole elegir entre dos opciones de fruta para merendar.',
'Sus manos ya tienen la fuerza suficiente para abrir algunos tipos de cierres sencillos.',
'El gateo sigue siendo el mejor ejercicio para su desarrollo cerebral y coordinación.',
'Si llora por la noche, puede ser por "ansiedad de separación" tardía; un beso y calma bastarán.',
'Es capaz de señalar partes de su cuerpo si se las repites a menudo (¿dónde está el ojo?).',
'Los juegos de construcción con bloques grandes ayudan a su visión espacial.',
'Ya puede beber de un vaso normal si lo sujetas tú; practica el control del flujo.',
'Empieza a mostrar preferencias por ciertos colores de ropa o de juguetes.',
'Si tienes perro o gato, vigila que el bebé no sea demasiado brusco con ellos; está aprendiendo empatía.',
'Notarás que se vuelve más "payaso" para llamar tu atención y hacerte reír.',
'La higiene de manos es vital ahora que toca absolutamente todo lo que hay por el suelo.',
'¡10 meses! Su motricidad fina le permite ya coger objetos muy pequeños con gran precisión.',
'Puede que intente soltarse de los muebles y quedarse de pie solo unos segundos.',
'Sus "primeras palabras" con significado suelen aparecer ahora (agua, pan, perro).',
'El concepto de "propiedad" aparece: "mío" será una de sus ideas principales pronto.',
'Le encanta que le leas el mismo cuento una y otra vez; la repetición es cómo aprenden.',
'Ya puede usar una cuchara con cierta eficacia, aunque la mitad acabe fuera.',
'Empieza a entender el concepto de "esperar" un momento, aunque le cueste mucho.',
'Los juguetes de arrastre (animales con ruedas y cuerda) son ideales para esta etapa.',
'Si da sus primeros pasos solo, no le fuerces; su cerebro decidirá cuándo se siente seguro.',
'La curiosidad por el contenido de los armarios de la cocina es infinita; deja uno con cosas seguras (tápers).',
'Puede empezar a tener miedo a ruidos fuertes como la aspiradora o el secador.',
'Notarás que el bebé tiene mucha más resistencia física y se cansa menos en los paseos.',
'Es capaz de obedecer órdenes simples como "¡No toques eso!" (aunque lo intente otra vez a los 2 minutos).',
'El juego con otros bebés sigue siendo "paralelo": juegan cerca pero no juntos.',
'Garabatos con ceras gruesas pueden aparecer; si aún no le interesan, no hay prisa.',
'Ya no necesita purés para nada; puede comer lo mismo que tú, cortado pequeño.',
'Empieza a identificar estados de ánimo en tu cara: sabe si estás triste o contento.',
'La coordinación para lanzar una pelota (aunque sin mucha puntería) ya está ahí.',
'Si viajas en coche, asegúrate de que la silla sigue siendo adecuada para su peso y altura.',
'Le fascina ver fotos de él mismo y de la familia en tu móvil o en álbumes.',
'Es capaz de reconocer canciones por la melodía inicial y empezar a aplaudir.',
'Si gatea, sus rodillas pueden estar un poco rojas; es normal, su piel se está curtiendo.',
'No le pongas zapatos con suela rígida todavía; la flexibilidad es clave para el arco del pie.',
'Ya puede usar el dedo índice para señalar algo que está lejos (un pájaro, un avión).',
'Empieza a entender que los objetos sirven para algo: el peine para el pelo, el teléfono al oído.',
'Si se frustra mucho con un juguete, enséñale a pedir ayuda en lugar de llorar.',
'La hora de la comida es un evento social; intégralo en la mesa con el resto de la familia.',
'Es normal que coma menos cantidad que antes; su crecimiento se está ralentizando.',
'Los juegos de agua (llenar y vaciar vasos) son su actividad favorita en el baño.',
'Empieza a mostrar sentido del humor; hará cosas "prohibidas" solo para ver tu reacción.',
'¡Solo falta un mes para el primer cumpleaños! Empieza a planificar algo sencillo.',
'Ya empieza a señalar con el dedo para pedir cosas. Valida su intención comunicativa diciendo siempre el nombre de lo que señala.',
'Hasta los 12 meses la leche principal sigue siendo materna o de fórmula; la de vaca aún no sustituye.',
'La miel sigue prohibida hasta los 12 meses por riesgo de botulismo; no la uses ni en trazas.',
'Muchos bebés dan sus primeros pasos independientes alrededor de esta fecha.',
'Su vocabulario suele tener entre 2 y 5 palabras con significado real.',
'Ya puede empezar a usar zapatos con suela un poco más firme para salir a la calle.',
'La transición del biberón al vaso debería ser casi total ahora para proteger sus dientes.',
'Es capaz de seguir el ritmo de una canción dando palmas o golpes suaves.',
'Su curiosidad por la comida es máxima; aprovecha para introducir sabores más complejos.',
'La "crisis del año" puede traer cambios en el sueño o en el apetito; es transitorio.',
'Ya sabe decir "adiós" con la mano de forma espontánea cuando alguien se va.',
'Puede empezar a usar cubiertos (tenedor de puntas romas) con cierta destreza.',
'Le encanta ayudar a recoger sus juguetes si lo conviertes en un juego con música.',
'Sus siestas se consolidan normalmente en una sola larga después de comer.',
'Empieza a entender conceptos de espacio: "dentro de la caja", "debajo de la mesa".',
'Es capaz de reconocerse perfectamente en el espejo y hacerse muecas.',
'El juego simbólico empieza: puede hacer que "bebe" de una taza de juguete vacía.',
'Si todavía toma pecho, ¡adelante! La OMS recomienda seguir hasta los 2 años o más.',
'Su peso suele ser el triple que al nacer y su altura ha crecido un 50%.',
'Empieza a mostrar una clara preferencia por uno de los dos padres según la actividad.',
'Es el momento de la revisión de los 12 meses y sus vacunas correspondientes.',
'Ya puede comer huevo entero (clara y yema) sin miedo a alergias si no las ha mostrado.',
'Le fascinan los juegos de "persecución": gatear tras él o que él te persiga.',
'Su capacidad de atención es mayor; puede estar 5-10 minutos concentrado en un juguete.',
'Empieza a intentar trepar al sofá o a las sillas; vigila siempre su espalda.',
'Los besos y abrazos empiezan a ser más "intencionados" y cariñosos.',
'No te agobies con la fiesta de cumple; el bebé se agobiará si hay demasiada gente y ruido.',
'Las rutinas siguen siendo su ancla de seguridad; intenta mantener los horarios de sueño.',
'Empieza a usar el dedo para pulsar botones de forma muy precisa.',
'¡Felicidades, papas! Has sobrevivido con éxito al primer año de crianza.',
'Ya no es un "bebé", ahora es un niño pequeño con mucha voluntad propia.',
'Si ya camina, su equilibrio mejorará cada día; las caídas son parte del aprendizaje.',
'Empieza a entender el concepto de "espera" un poco mejor, aunque sigue siendo difícil.',
'Su comunicación es una mezcla de palabras, gestos y sonidos muy eficaz.',
'Le encanta "leer" sus propios cuentos pasando las páginas una a una (aunque sean de cartón).',
'A partir del año, la miel ya es segura con moderación; sigue priorizando comida real frente al azúcar.',
'El juego con arena o tierra en el parque es una experiencia sensorial increíble para él.',
'Empieza a intentar quitarse los calcetines o los zapatos solo.',
'Sus rabietas pueden ser más frecuentes porque su mente va más rápido que su lenguaje.',
'Es capaz de identificar a los animales en los dibujos y hacer sus sonidos.',
'Si introduces leche de vaca entera, que sea un alimento más, no la base de la dieta; prioriza comida sólida.',
'Empieza a mostrar interés por los lápices y a intentar hacer rayas en el papel.',
'Si le pides algo, ya puede ir a buscarlo a otra habitación y traértelo.',
'Le fascinan los cierres de cremallera y los botones grandes; déjale practicar.',
'Su personalidad es cada vez más clara: ¿es observador, lanzado, tranquilo o inquieto?',
'Ya puede beber con una pajita; es un ejercicio excelente para los músculos de la cara.',
'Empieza a entender el concepto de "secuencia": primero el baño, luego el pijama.',
'Los juegos de encajar figuras geométricas (círculo, cuadrado) empiezan a salirle bien.',
'Le encanta que le lleves de la mano para caminar por la calle.',
'Su curiosidad por "qué hay dentro" de las cosas le llevará a intentar desmontar juguetes.',
'Es capaz de señalar tres o cuatro partes de su cuerpo con precisión.',
'Empieza a imitar gestos complejos de los adultos, como hacer que habla por teléfono.',
'Notarás que empieza a tener "amigos" preferidos en el parque.',
'Su vocabulario receptivo es enorme: entiende casi todo lo que dices en contexto.',
'La hora de dormir puede volverse un poco de "negociación"; mantén el límite con cariño.',
'Ya puede comer fruta con piel (bien lavada) si es fina y él tiene muelas.',
'Le encanta subir y bajar de cosas pequeñas; los escalones del parque son un reto.',
'Empieza a mostrar interés por la ropa; puede señalar los zapatos que quiere ponerse.',
'El uso del "No" se vuelve su herramienta favorita para marcar su independencia.',
'Disfruta de esta etapa: tu bebé ya es un pequeño compañero de aventuras.',
'Si ya camina con soltura, empezará a intentar llevar objetos pesados de un lado a otro al mismo tiempo.',
'Le encanta meter llaves en cerraduras o monedas en ranuras; su precisión mejora cada día.',
'Es capaz de pasar las páginas de un libro una a una, aunque a veces se salte alguna.',
'Empieza a identificar objetos por su uso: "tráeme el zapato" y sabrá qué buscar.',
'Los juegos de construcción ahora son más de "destrucción": le divierte más tirar tu torre que hacerla.',
'Notarás que empieza a comer con más limpieza, aunque todavía use las manos para lo que se le escapa.',
'Es un gran momento para introducir juguetes de empujar (como carritos de la compra de juguete).',
'Ya puede entender la diferencia entre "dentro" y "fuera" con claridad.',
'Su vocabulario receptivo es como una esponja; evita decir palabras que no quieras que repita.',
'Empieza a mostrar interés por los animales reales; si tienes mascota, enséñale a acariciarla "suave".',
'Ya puede beber de un vaso sin boquilla si le ayudas a sujetarlo.',
'Le encanta que le persigas por la casa; sus risas te indicarán que es su juego top.',
'Empieza a imitar gestos de autocuidado, como intentar lavarse la cara con una esponja.',
'La siesta de la tarde se vuelve sagrada; si se la salta, la tarde será "complicada".',
'Es capaz de garabatear círculos o líneas con ceras de colores; el papel grande en el suelo es ideal.',
'Ya puede señalar 5 o 6 partes de su cuerpo con precisión.',
'Notarás que empieza a tener "preferencia de mano" (diestro o zurdo), aunque puede cambiar.',
'Los juguetes con ruedas pequeñas (coches) son fascinantes para él ahora.',
'Empieza a entender que las fotos en el móvil representan personas reales que conoce.',
'Su equilibrio mejora tanto que puede intentar bailar dando vueltas (y marearse un poco).',
'Es capaz de seguir instrucciones de un solo paso sin apoyo gestual.',
'Empieza a "ayudarte" a recoger la ropa de la lavadora; le encanta sentirse útil.',
'Su curiosidad por lo que hay "arriba" le llevará a intentar trepar por los cajones.',
'La hora del baño es un campo de experimentos: ¿qué flota y qué se hunde?',
'Empieza a mostrar timidez ante extraños, incluso con personas que ha visto antes.',
'Ya puede comer trozos de fruta más grandes; su mandíbula es mucho más fuerte.',
'Le fascina abrir y cerrar puertas; pon protectores para que no se pille los dedos.',
'Empieza a usar palabras para expresar necesidades básicas (más, agua, pan).',
'Los juegos de pelotas son excelentes para su coordinación ojo-pie.',
'El desorden es su forma de aprender física. Si tira la comida al suelo o golpea dos juguetes, no está siendo "malo"; está testeando la gravedad y la acústica de su entorno.',
'Aparecen los primeros gustos selectivos: puede que solo quiera comer cosas de un color específico.',
'Empezará a usar gestos complejos, como llevarte de la mano hacia lo que quiere.',
'Es capaz de reconocer su nombre incluso si hay ruido de fondo o estás lejos.',
'Los rompecabezas de madera de piezas grandes (encajables) empiezan a ser pan comido.',
'Ya puede caminar hacia atrás algunos pasos; es un hito de equilibrio importante.',
'Su capacidad de atención en un cuento sube a los 10-15 minutos si hay dibujos llamativos.',
'Empieza a entender el concepto de "esperar" un poquito mejor (solo un poquito).',
'Le encanta esconder cosas en sitios raros (zapatos, macetas); revisa antes de salir de casa.',
'Ya puede subir escalones gateando o de la mano con mucha seguridad.',
'La leche sigue siendo importante, pero su dieta ya debe ser 100% variada.',
'Empezará a imitar tareas complejas: "barrer", "hablar por teléfono" o "cocinar".',
'Su sentido del humor se vuelve más sofisticado; hará tonterías para que te rías.',
'Es capaz de identificar a familiares en fotos de grupo.',
'Los juegos con otros niños siguen siendo "en paralelo", pero se miran mucho más.',
'Notarás que empieza a tener un juguete "de consuelo" que quiere llevar a todas partes.',
'Ya puede usar el tenedor para pinchar trozos blandos de comida.',
'Empieza a mostrar frustración si no le entiendes lo que intenta decirte.',
'Le fascinan los libros que tienen sonidos de la naturaleza o de la ciudad.',
'Es el momento ideal para empezar a enseñarle a lavarse las manos solo.',
'Su capacidad para trepar al sofá es ahora una habilidad experta; vigilancia máxima.',
'Empieza a entender frases negativas ("no hay más", "no se puede").',
'Las rutinas le dan la paz que necesita para no tener tantas rabietas.',
'Le encanta jugar con cajas de cartón vacías; a veces son mejores que el juguete que venía dentro.',
'Ya puede lanzar una pelota con las manos hacia adelante con cierta dirección.',
'Empieza a identificar sonidos del exterior (una ambulancia, un perro ladrando).',
'Su sueño puede verse alterado por los hitos motores: a veces "practican" dormidos.',
'Es capaz de señalar un pájaro en el cielo o un perro a lo lejos.',
'No uses el "no" para todo; reserva esa palabra para peligros reales.',
'Empieza a mostrar interés por los zapatos de los adultos e intentará ponérselos.',
'¡15 meses! Su independencia crece y su velocidad también.',
'El vocabulario hablado suele crecer de golpe: puede tener entre 10 y 20 palabras claras.',
'Empieza a entender conceptos opuestos: grande/pequeño, frío/calor.',
'Ya puede correr, aunque su forma de hacerlo sea un poco "patosa" y con los brazos abiertos.',
'Le encanta que le cantes canciones con coreografía (como "Cinco lobitos" o "El patio de mi casa").',
'Es capaz de apilar 3 o 4 bloques sin que se le caigan.',
'Empezará a usar su propia cuchara con mucha más precisión hacia la boca.',
'Su curiosidad por el cuerpo humano aumenta: te señalará la nariz, la boca y los ojos.',
'Ya puede distinguir perfectamente entre lo que es comida y lo que no (aunque lo pruebe todo).',
'Le fascina ver a otros niños más mayores jugar; aprende por observación pura.',
'Empieza a tener una "canción favorita" que te pedirá una y otra vez.',
'Es capaz de reconocer objetos en los libros aunque sean dibujos abstractos.',
'Notarás que tiene mucha más fuerza para empujar sillas o mover muebles pequeños.',
'Ya puede bajar escaleras sentado o de espaldas con seguridad.',
'Empieza a mostrar interés por "ayudar" a poner la mesa (cosas que no rompa).',
'Su capacidad de imitación es tan alta que repetirá tus gestos cuando estás enfadado o alegre.',
'Es normal que tenga días de "mamitis" o "papitis" aguda; necesita recargar su seguridad.',
'Los juegos de arena le permiten practicar la psicomotricidad fina (llenar cubos).',
'Empieza a entender que las cosas tienen un lugar: "guarda esto en su sitio".',
'Ya puede identificar a los animales por el sonido que hacen sin verlos.',
'Su independencia al comer le hace rechazar que le des tú la comida.',
'Es capaz de garabatear con más intención, intentando no salirse del papel.',
'Notarás que su risa es mucho más social y busca cómplices.',
'Empieza a mostrar empatía: si ve a otro niño llorar, puede ponerse triste o mirarle con preocupación.',
'Ya puede beber con pajita con total control.',
'Le encanta jugar a que es un animal (gatear como un gato, rugir como un león).',
'Su curiosidad por la naturaleza es infinita: una hormiga en el suelo es un espectáculo.',
'Empieza a entender el concepto de "mío" con mucha fuerza.',
'Ya puede quitarse prendas sencillas como el gorro o los calcetines.',
'Los miedos pueden empezar a aparecer (oscuridad, sombras); valídalos siempre.',
'¡Tu bebé ya es un pequeño explorador con ganas de comerse el mundo!',
'Entramos en la fase de "yo solo": querrá hacer todo sin tu ayuda aunque tarde el triple.',
'Su equilibrio es tan bueno que puede intentar chutar una pelota sin caerse.',
'Empieza a entender instrucciones que implican dos pasos relacionados ("coge el cuento y ponlo en la mesa").',
'Le encanta bailar con música rítmica; moverá todo el cuerpo, no solo los brazos.',
'Ya puede identificar colores básicos si se los repites a menudo durante los juegos.',
'Su vocabulario se enriquece con adjetivos sencillos (sucio, rico, feo).',
'Empieza a tener noción de la propiedad: sabe qué zapatos son de papá y cuáles de mamá.',
'Es capaz de subir a una silla pequeña y sentarse correctamente solo.',
'Notarás que el niño tiene periodos de juego concentrado más largos (hasta 20 minutos).',
'Ya puede comer casi cualquier textura, pero corta siempre las cosas muy duras.',
'Le fascina "limpiar" cristales o espejos; dale un trapo seco y se entretendrá mucho.',
'Empieza a usar el pronombre "yo" o su propio nombre para referirse a sí mismo.',
'Su destreza con los cierres de velcro es total; se quitará los zapatos en el momento menos oportuno.',
'Los juegos de "papá Noel" o esconder regalos pequeños le encantan.',
'Ya puede distinguir entre un perro real y un peluche de perro.',
'Empieza a mostrar interés por ir al baño cuando tú vas; es el inicio de la curiosidad por el orinal.',
'Es capaz de reconocer canciones infantiles por las primeras dos notas.',
'Su fuerza para lanzar objetos es mayor; enséñale que "las cosas no se tiran".',
'Notarás que le gusta mucho la repetición: mismo cuento, misma comida, misma ruta al parque.',
'Ya puede saltar hacia abajo desde un escalón muy bajito (con ayuda).',
'Empieza a entender el concepto de "mañana" o "después", aunque su noción del tiempo sea escasa.',
'Le encanta jugar con plastilina (vigila que no se la coma); es genial para sus dedos.',
'Su comunicación gestual se vuelve muy sofisticada para pedir lo que quiere.',
'Ya puede abrir algunos botes de rosca sencillos; ten cuidado con lo que hay dentro.',
'Empieza a mostrar preferencia por ciertos programas de TV o videos cortos; limita su uso.',
'Es capaz de identificar sonidos de la casa: el timbre, el microondas, el agua corriendo.',
'Su capacidad para trepar es ahora su mayor peligro; revisa la estabilidad de las estanterías.',
'Le encanta que le leas cuentos antes de dormir; es su momento de calma favorito.',
'Ya puede empezar a usar el cepillo de dientes con un poco de pasta (tamaño grano de arroz).',
'Tu hijo es ahora un espejo en tiempo real. Si quieres que aprenda a saludar, a dar las gracias o a probar un alimento nuevo, asegúrate de que te vea a ti haciéndolo primero.',
'A los 17 meses, el "yo solo" empieza a ser ley. Aunque tengas prisa por salir de casa, intenta darle 2 minutos de margen para que intente ponerse un zapato o subir un escalón sin ayuda.',
'Muchos niños tienen la "explosión del lenguaje" este mes: aprenden palabras nuevas cada día.',
'Puede empezar a unir dos palabras para formar frases cortas ("más agua", "papá calle").',
'Ya camina con total seguridad, incluso deprisa o intentando trotar.',
'Su capacidad para imitar acciones domésticas es total: querrá "cocinar" o "planchar" como tú.',
'Es capaz de subir escaleras de pie agarrado a la barandilla o a tu mano.',
'Los juegos de encajar piezas complejas ya son un reto divertido para él.',
'Empieza a mostrar interés por otros niños y puede intentar compartir algún juguete (aunque le cueste).',
'Ya puede usar una cuchara y un tenedor con bastante limpieza.',
'Su personalidad es arrolladora; tiene gustos muy definidos y los defiende.',
'Es capaz de identificar 10 o más objetos comunes en un libro.',
'Notarás que empieza a tener menos necesidad de siestas largas, aunque una al día sigue siendo vital.',
'Ya puede lavarse las manos y la cara con un poco de ayuda.',
'Le fascina jugar con agua: llenar cubos, regar plantas o simplemente chapotear.',
'Empieza a entender el concepto de "ayudar" de forma real: "trae el pañal sucio".',
'Su capacidad de memoria a largo plazo aumenta: recuerda dónde estuvisteis ayer.',
'Ya puede chutar una pelota en movimiento sin perder el equilibrio.',
'Empieza a mostrar curiosidad por los genitales y las diferencias entre niños y niñas.',
'Es capaz de usar el orinal de forma ocasional si le invitas, aunque todavía no controle.',
'Los libros de "busca y encuentra" son ideales para esta etapa de agudeza visual.',
'Notarás que el niño tiene mucha más fuerza de voluntad: el "no" es su palabra de poder.',
'Ya puede quitarse prendas de ropa sencillas (pantalones de goma, zapatos).',
'Empieza a mostrar interés por los lápices de colores y a intentar "colorear" dibujos.',
'Su sentido del equilibrio le permite caminar sobre superficies irregulares (césped, arena).',
'Es capaz de entender instrucciones negativas complejas ("no toques eso que quema").',
'Le encanta jugar con pompas de jabón; intentará atraparlas y soplarlas.',
'Su comunicación con otros adultos (abuelos, tíos) es mucho más fluida.',
'Ya puede subir y bajar del sofá o de su silla de comer sin ayuda.',
'Empieza a mostrar orgullo cuando consigue algo difícil ("¡mira, mamá y papá!").',
'¡18 meses! Has llegado a los tres cuartos del camino hacia los 2 años.',
'A los 18 meses, su equilibrio le permite subir escaleras alternando los pies si le das la mano.',
'Empieza a usar adjetivos para describir cosas: "grande", "sucio", "frío".',
'Le encanta ayudar en tareas reales: "lleva esto a la basura" o "trae tus zapatos".',
'Ya puede completar puzzles de 3 o 4 piezas de encaje con facilidad.',
'Su juego simbólico es más complejo: ahora "habla" por teléfono con personas imaginarias.',
'Identifica perfectamente objetos por su función: "¿con qué nos peinamos?".',
'Notarás que empieza a tener "preferencia de mano" más marcada, aunque aún puede alternar.',
'Ya puede correr esquivando obstáculos sin caerse tanto.',
'Le fascina jugar con otros niños, aunque el "compartir" siga siendo un reto emocional.',
'Empieza a entender conceptos de cantidad como "uno" o "muchos".',
'Ya puede identificar 5 o 6 colores si se los repites a menudo.',
'Su curiosidad por los animales aumenta; identifica sonidos de animales salvajes en libros.',
'Ya puede saltar con los dos pies juntos desde un escalón muy bajo.',
'Empieza a mostrar preferencia por ciertos cuentos específicos antes de dormir.',
'Le fascina jugar con plastilina; estimula su motricidad fina y su imaginación.',
'Es capaz de reconocer su ropa y sabe de quién es cada prenda en casa.',
'Notarás que empieza a tener un "mejor amigo" o compañero favorito en el parque.',
'Ya puede usar el tenedor con soltura para pinchar alimentos de diferentes durezas.',
'Empieza a entender el concepto de "turno" en el juego, aunque necesita que lo guíes.',
'Le encanta que le narres lo que haces: "Ahora papá está preparando la cena".',
'Es capaz de imitar sonidos de motores: coches, aviones o la batidora.',
'Ya puede abrir puertas con manivela; revisa los cierres de seguridad de casa.',
'Empieza a mostrar interés por los lápices de colores; sus garabatos ya tienen forma circular.',
'Su capacidad de memoria le permite recordar dónde guardaste un juguete ayer.',
'Ya puede beber de una taza normal con una sola mano (con supervisión).',
'Le fascina clasificar objetos por tamaños: del más grande al más pequeño.',
'Empieza a usar el pronombre "yo" para referirse a sí mismo.',
'Es capaz de seguir instrucciones de dos pasos: "Recoge el juguete y ponlo en la caja".',
'Su sentido del ritmo mejora: puede seguir una canción dando golpecitos con el pie.',
'¡19 meses! Tu bebé ya tiene la energía de un pequeño explorador incansable.',
'A los 19 meses, su vocabulario suele tener una "explosión" de palabras nuevas cada semana.',
'Ya puede agacharse para recoger algo y levantarse sin perder el equilibrio.',
'Empieza a mostrar interés por lavarse los dientes "solo" después de que tú lo hagas.',
'Le encanta jugar a los disfraces: ponerse gorros, gafas o zapatos de los adultos.',
'Es capaz de identificar a familiares en fotos antiguas o digitales con alegría.',
'Ya puede chutar una pelota en movimiento sin caerse.',
'Empieza a expresar sus emociones básicas con palabras: "contento", "triste", "miedo".',
'Le fascina jugar con agua: llenar y vaciar recipientes le enseña sobre volumen.',
'Su capacidad para trepar al sofá es ahora una habilidad experta; vigila las caídas.',
'Ya puede usar la cuchara sin que se le caiga casi nada de comida.',
'Empieza a entender el concepto de "dentro", "fuera", "arriba" y "abajo" con precisión.',
'Le encanta imitar los ruidos de la casa: la aspiradora, el timbre o el microondas.',
'Ya puede caminar de puntillas durante unos segundos si juega contigo.',
'Es capaz de reconocer canciones infantiles solo por los primeros segundos de melodía.',
'Empieza a mostrar empatía: si te ve "triste", puede intentar darte un beso o un juguete.',
'Ya puede quitarse prendas de ropa sencillas sin ayuda (pantalones de chándal).',
'Le fascina el juego de "escondite" con objetos; búscalo tú y que él lo encuentre.',
'Su curiosidad por los bichos del suelo es infinita; vigila que no se los coma.',
'Ya puede empezar a usar el orinal de forma ocasional si muestra interés.',
'Empieza a tener noción de la propiedad: "eso es de mamá", "eso es de bebé".',
'Es capaz de apilar 5 o 6 bloques sin que la torre se derrumbe.',
'Le encanta ayudar a "barrer" o "limpiar" el polvo con un trapo seco.',
'Ya puede identificar animales por su sombra o silueta en los libros.',
'Su comunicación gestual se une a las palabras para hacerse entender mejor.',
'Empieza a mostrar interés por la comida de "mayores" con texturas más complejas.',
'Es capaz de abrir cremalleras grandes en mochilas o chaquetas.',
'Le fascina ver fotos de él mismo cuando era un recién nacido.',
'Ya puede saltar desde una altura pequeña cayendo con ambos pies.',
'Empieza a entender el concepto de "después": "después de la siesta iremos al parque".',
'¡20 meses! Su personalidad brilla cada día con más fuerza.',
'A los 20 meses, ya identifica los colores primarios con bastante éxito.',
'Empieza a formar frases sencillas de dos palabras: "más pan", "mamá calle".',
'Le encanta jugar con arena; llenar cubos y hacer "pasteles" mejora su motricidad.',
'Ya puede abrir botes con tapa de rosca que no sean de seguridad.',
'Su equilibrio le permite caminar sobre superficies irregulares como el césped.',
'Empieza a mostrar interés por los rompecabezas de formas geométricas (círculo, triángulo).',
'Es capaz de reconocer sonidos de la calle: una ambulancia, una moto, un pájaro.',
'Ya puede lavarse las manos y la cara con un poco de supervisión.',
'Le fascina "leer" sus cuentos favoritos a sus muñecos o peluches.',
'Empieza a usar el pronombre "mío" con mucha autoridad; está marcando su espacio.',
'Ya puede subir escaleras apoyándose solo con una mano en la pared.',
'Es capaz de identificar qué objeto falta si escondes uno de un grupo de tres.',
'Le encanta ayudar a sacar la ropa limpia de la lavadora y ponerla en el cesto.',
'Su curiosidad por las herramientas de papá (destornilladores, llaves) es máxima; usa juguetes.',
'Ya puede comer con tenedor y cuchara alternándolos según la comida.',
'Empieza a entender el concepto de "parar" inmediatamente cuando se lo pides.',
'Le fascina jugar con pompas de jabón e intentar atraparlas sin romperlas.',
'Es capaz de garabatear líneas verticales y horizontales con intención.',
'Ya puede distinguir entre "frío" (hielo) y "caliente" (comida) con seguridad.',
'Empieza a mostrar orgullo por sus logros: "¡mira mamá, mira!".',
'Su memoria a largo plazo le permite recordar el nombre de niños que ve poco.',
'Ya puede quitarse los zapatos de velcro solo en cuanto llega a casa.',
'Le encanta jugar con cajas de cartón; pueden ser un coche, un barco o una cueva.',
'Empieza a entender que las acciones tienen consecuencias: "si tiras el agua, se moja el suelo".',
'Es capaz de reconocer las marcas de sus alimentos favoritos en el supermercado.',
'Ya puede beber de una botella pequeña con boquilla de deporte sin ayuda.',
'Le fascina imitar los gestos que haces cuando hablas por el móvil.',
'Su coordinación le permite empezar a pedalear en un triciclo (aunque le cueste avanzar).',
'Empieza a mostrar interés por los libros que tienen solapas o texturas ocultas.',
'¡21 meses! Un pequeño motor de curiosidad que no para ni un segundo.',
'A los 21 meses, sus rabietas pueden ser intensas porque ya sabe exactamente lo que quiere.',
'Empieza a usar el nombre de otras personas para llamar su atención.',
'Le encanta jugar a que es un animal: ruge como león o salta como conejo.',
'Ya puede identificar 3 o 4 partes del cuerpo menos comunes (rodilla, codo, barbilla).',
'Es capaz de apilar hasta 8 bloques en una torre antes de que caiga.',
'Empieza a mostrar interés por "colorear" dibujos, aunque todavía se salga mucho.',
'Ya puede abrir puertas que no tienen pomo (empujando o tirando).',
'Le fascina jugar con la pelota: lanzarla, chutarla y perseguirla sin parar.',
'Su capacidad de atención en una actividad sube hasta los 20 minutos si le gusta.',
'Ya puede identificar qué ropa se pone en cada parte del cuerpo.',
'Empieza a usar el "No" no solo como rechazo, sino como afirmación de su voluntad.',
'Es capaz de reconocer el camino hacia el parque o la casa de los abuelos.',
'Le encanta ayudar a regar las plantas con una regadera pequeña de juguete.',
'Ya puede bajar escaleras de pie si se agarra con las dos manos.',
'Empieza a mostrar miedos más específicos (un perro grande, un ruido de trueno).',
'Es capaz de identificar objetos por su olor si son muy característicos (limón, jabón).',
'Le fascina jugar con construcciones tipo Lego de piezas grandes (Duplo).',
'Ya puede comer fruta entera (manzana, pera) con piel si está bien lavada.',
'Empieza a entender el concepto de "compartir" un juguete durante un rato corto.',
'Su vocabulario receptivo es casi completo: entiende casi todo lo que dices en contexto.',
'Ya puede lavarse los dientes con muy poca ayuda, aunque luego debas repasárselos.',
'Le encanta que le cantes canciones que impliquen gestos con las manos.',
'Es capaz de identificar a los personajes de sus dibujos favoritos por su voz.',
'Ya puede correr con seguridad y frenar de golpe sin caerse de bruces.',
'Empieza a mostrar interés por la procedencia de las cosas: "¿de dónde viene esto?".',
'Su coordinación ojo-mano le permite ensartar cuentas grandes en un cordón.',
'Le fascina "cocinar" con sus juguetes mientras tú haces la comida real.',
'Ya puede subir a un tobogán pequeño y tirarse sentado sin miedo.',
'Empieza a mostrar preferencias por el color de sus juguetes o de su ropa.',
'¡22 meses! Su mundo emocional es cada vez más rico y complejo.',
'A los 22 meses, su comunicación es una mezcla muy eficaz de palabras y gestos.',
'Ya puede saltar hacia adelante con los dos pies, como una pequeña rana.',
'Empieza a mostrar mucho interés por el orinal; es el momento de las primeras pruebas.',
'Le encanta ayudar a poner la mesa con cosas que no pesen (servilletas, pan).',
'Es capaz de completar rompecabezas de 6 piezas si le ayudas un poco al principio.',
'Ya puede identificar qué objetos son para el baño, para la cocina o para el dormitorio.',
'Su curiosidad por el funcionamiento de las cosas le lleva a intentar "arreglar" juguetes.',
'Empieza a usar frases de tres palabras: "Mamá, quiero agua".',
'Le fascina jugar con barro o masa sensorial; la suciedad es aprendizaje.',
'Ya puede caminar hacia atrás y de lado con total seguridad.',
'Es capaz de reconocer letras o números si se los has enseñado como un juego.',
'Empieza a entender el concepto de "esperar" un poco mejor (hasta 2 o 3 minutos).',
'Le encanta que le leas cuentos largos con una trama sencilla.',
'Ya puede abrir y cerrar botes de plástico con tapa a presión.',
'Su coordinación le permite empezar a chutar una pelota hacia un objetivo (gol).',
'Empieza a mostrar interés por la higiene personal: "tengo las manos sucias".',
'Es capaz de identificar a los animales por su hábitat básico (en el agua, en el campo).',
'Ya puede subir y bajar del sofá o de su cama pequeña sin ayuda alguna.',
'Le fascina imitar los gestos de los hermanos mayores o de otros niños.',
'Su sentido del equilibrio es tan bueno que puede intentar caminar sobre un bordillo bajo.',
'Empieza a usar adverbios de lugar: "aquí", "allí", "arriba", "lejos".',
'Ya puede usar tijeras de plástico para niños (con supervisión) para hacer flecos.',
'Le encanta jugar a las "comiditas" y ofrecerte lo que ha preparado.',
'Es capaz de reconocer el logo de su tienda o restaurante favorito en la calle.',
'Ya puede ponerse el abrigo solo si tú le sujetas las mangas al principio.',
'Empieza a mostrar preferencias por el orden de sus cosas: "esto va aquí".',
'Su memoria le permite recordar canciones enteras y canturrearlas.',
'Le fascina ver cómo funcionan las máquinas: el camión de la basura es su héroe.',
'Ya puede identificar qué objetos son "peligrosos" porque queman o cortan.',
'Tu peque ya empieza a entender secuencias temporales. Usa el "primero esto, luego aquello".',
'Aplica el "Poder de la Elección Limitada". Si se niega a colaborar, no impongas; ofrece dos opciones válidas: "¿Quieres lavarte los dientes antes o después del pijama?"',
'Su vocabulario suele tener ya entre 50 y 200 palabras según cada niño.',
'Ya puede formar frases complejas y expresar necesidades, deseos y miedos.',
'Es capaz de saltar desde un escalón y caer de pie con total equilibrio.',
'Empieza a jugar "con" otros niños de forma cooperativa, no solo al lado.',
'Ya puede empezar a dejar el pañal durante el día si muestra señales de madurez.',
'Le encanta subir y bajar escaleras alternando los pies sin ayuda de las manos.',
'Su imaginación vuela: cualquier objeto puede ser un avión o un dinosaurio.',
'Ya puede usar cubiertos de metal para niños con total autonomía.',
'Es capaz de identificar y nombrar la mayoría de los objetos de su entorno diario.',
'Empieza a entender conceptos temporales como "mañana", "tarde" y "noche".',
'Ya puede ponerse y quitarse los pantalones de goma él solo.',
'Le fascina ayudar en la cocina: remover la masa o lavar las verduras.',
'Su coordinación ojo-mano le permite construir torres de más de 10 bloques.',
'Ya puede identificar sus propios sentimientos y los de los demás.',
'Empieza a mostrar interés por los juegos de mesa muy sencillos (lotería de animales).',
'Es capaz de seguir una historia compleja en un libro o en una película corta.',
'Ya puede pedalear en un triciclo con fuerza y dirección.',
'Le encanta "leer" cuentos él solo, inventándose la historia según los dibujos.',
'Su sentido del humor es fantástico: entiende las bromas y las situaciones cómicas.',
'Ya puede lavarse los dientes, la cara y las manos con mínima ayuda.',
'Empieza a entender el concepto de "reglas" en el juego y en casa.',
'Es capaz de reconocer las letras de su propio nombre en un texto.',
'Ya puede subir a estructuras de juego complejas en el parque (con vigilancia).',
'Le fascina explorar la naturaleza: recoger piedras, hojas y observar insectos.',
'Su capacidad de memoria le permite recordar qué hizo en su fiesta de cumple.',
'Ya puede expresar su opinión sobre la ropa que quiere ponerse.',
'Empieza a mostrar interés por aprender canciones en otros idiomas.',
'Es capaz de identificar qué objetos son pesados y cuáles son ligeros.',
'Ya puede abrir y cerrar puertas con llave (¡atención a la seguridad!).',
'Le encanta jugar a que es un superhéroe o un personaje de cuento.',
'Su coordinación le permite empezar a lanzar pelotas con puntería.',
'Ya puede identificar las partes del cuerpo menos visibles (muñeca, tobillo).',
'Empieza a entender que el dinero sirve para comprar cosas (juego de tiendas).',
'Es capaz de seguir instrucciones complejas de tres pasos seguidos.',
'Algunos niños usan el orinal gran parte del día; otros necesitan más tiempo: sigue su ritmo, sin presión.',
'Le fascina ver cómo crecen las plantas o cómo cambian las estaciones.',
'Su vocabulario se enriquece con palabras de cortesía: por favor, gracias, perdón.',
'Es capaz de reconocer las señales de tráfico más comunes cerca de casa.',
'¡Dos años cumplidos! Tu hijo es una persona única y maravillosa. ¡Felicidades papas!',
];
