// Auto-translated ES→EN for daily tips (same count as Spanish).
// ignore_for_file: lines_longer_than_80_chars

const List<String> kSabiasQueTipsEn = [
'Skin-to-skin contact helps stabilize the newborn\\\\\\\\\\\\\\\'s heart rate.',
'Don\\\\\\\\\\\\\\\'t use alcohol wipes; Neutral soap and water or water wipes are best.',
'Meconium (first poop) is sticky; apply a little baby oil to clean it better.',
'Your baby has no schedule; Breastfeeding (breast or formula) should be on demand.',
'The umbilical cord usually falls between 5 and 15 days; keep it dry.',
'If he cries a lot, white noise (dryer, extractor hood) can calm him down.',
'Babies are born with blurred vision; They only see well from 25 cm away.',
'Don\\\\\\\\\\\\\\\'t worry about his cold hands and feet; Your circulatory system is still maturing.',
'Hiccups are very common and do not harm them; Don\\\\\\\\\\\\\\\'t try to scare him away.',
'The "15-day crisis" is real: you will want to eat a lot more to increase production.',
'Babies don\\\\\\\\\\\\\\\'t need a pillow; Your neck should be flat to breathe well.',
'If you have gas, gently draw your legs toward your chest ("bicycle" effect).',
'Bathing doesn\\\\\\\\\\\\\\\'t have to be daily; 3 times a week is enough at first.',
'Don\\\\\\\\\\\\\\\'t cut his nails yet; They are very soft and stick to the skin. Use cardboard files.',
'It is normal to lose weight the first few days; You will get it back in the second week.',
'Vitamin D is essential: give it every day as instructed by your pediatrician.',
'Do not cover the baby excessively; If your neck is sweaty, you have extra clothes.',
'Your baby recognizes your voice from the womb; Talk to him a lot, even if he doesn\\\\\\\\\\\\\\\'t respond.',
'Sneezing is your way of clearing your nose of dust or lint; It\\\\\\\\\\\\\\\'s not a cold.',
'The grasping reflex (grabbing your finger) is instinctive and very strong.',
'If you breastfeed, your diet should be varied; There are no prohibited foods (except alcohol).',
'A breastfed baby\\\\\\\\\\\\\\\'s poop is usually liquid and lumpy; It\\\\\\\\\\\\\\\'s normal.',
'Sleep when the baby sleeps; Accumulated fatigue is the father\\\\\\\\\\\\\\\'s worst enemy.',
'The sucking instinct calms them; Sometimes they just want to suck even if they are not hungry.',
'Don\\\\\\\\\\\\\\\'t use fabric softener on your clothes; It may irritate your extremely sensitive skin.',
'Infant acne are pimples caused by your hormones; Don\\\\\\\\\\\\\\\'t touch them, they disappear on their own.',
'If the baby is irritable, a walk outdoors is usually a "saint\\\\\\\\\\\\\\\'s hand."',
'Do not allow them to kiss the baby on the face or hands to avoid spreading viruses.',
'The walking reflex: if you hold him upright, he will move his legs as if he were walking.',
'Cramps usually appear at the end of the day; stay calm, you are his refuge.',
'Around 6 weeks the first "social smile" arrives; enjoy it!',
'He begins to make guttural sounds like "ajó"; Imitate him to encourage his language.',
'Tummy time helps strengthen your neck; do it 2 min several times.',
'Your eyes may sometimes cross (functional strabismus); It is normal up to 4 months.',
'Start following objects with your eyes; use toys of contrasting colors.',
'You can now cut his nails with round-tip scissors while he sleeps.',
'If you use a pacifier, wait until breastfeeding is established to introduce it.',
'The hands are no longer always in fists; start opening them and exploring them.',
'Cradle cap on the head does not itch; It is removed little by little with oil and gentle brushing.',
'If he cries inconsolably, check to see if he has a thread or hair wrapped around his toe.',
'It is the month of the first vaccines; Have children\\\\\\\\\\\\\\\'s paracetamol on hand in case they get a fever.',
'You will notice that he drools more; you are discovering your salivary glands.',
'Begin to distinguish primary colors, especially red.',
'Play soft music; Helps your cognitive and auditory development.',
'Massages before bathing reduce stress for baby and dad.',
'Don\\\\\\\\\\\\\\\'t force him to sit; His spine does not yet have the necessary strength.',
'If you spit up some milk after eating, it is normal as long as you gain weight.',
'He begins to show a preference for human faces over objects.',
'Nighttime crying may be due to overstimulation during the day.',
'Let him experiment with different textures of clothing (cotton, soft wool).',
'Crib mobiles should be at a distance where you cannot reach them.',
'If he falls asleep in the car, move him to his crib as soon as you get home.',
'Encourage eye contact while changing his diaper; It is a moment of connection.',
'Begin to recognize the routine: bath -> pajamas -> dinner -> sleep.',
'It is normal for you to go several days without pooping if you breastfeed only; It\\\\\\\\\\\\\\\'s not constipation.',
'Ergonomic carrying is ideal for keeping your hands free and your baby calm.',
'Don\\\\\\\\\\\\\\\'t use walkers; They are dangerous and harmful to their motor development.',
'Avoid strong perfumes around the baby; His sense of smell is very sensitive.',
'He starts kicking hard; Make sure the diaper does not squeeze his abdomen.',
'Your baby already knows who his main attachment figure is.',
'On his tummy he already tries to lift his head and chest; it strengthens the neck, the base for future movement.',
'He begins to discover his hands: he looks at them, sucks on them and joins them in the center of his body.',
'Hand-eye coordination improves; He tries to reach for toys even though sometimes he misses.',
'If you talk to him from the side of the room, he should already turn his head to look for you.',
'Babbling is more complex: add sounds like "p", "b" and "m".',
'It is a good time to introduce a floor activity gym.',
'He now distinguishes color nuances better; shiny toys fascinate him.',
'Sleep begins to consolidate a little more at night, although each baby is different.',
'You will notice that he has more strength in his legs and kicks with a lot of energy.',
'If you have a lot of saliva, it may be due to the maturation of the glands, not necessarily teeth.',
'He loves social contact; He smiles at almost anyone who cuddles him.',
'Start imitating your facial expressions; Stick your tongue out and see if he tries.',
'Cloth books with different textures are ideal for curious hands.',
'Avoid leaving it in the hammock for many hours; The ground is where he learns the most.',
'If he takes a bottle, check that the nipple has the appropriate flow rate for his age.',
'The "eighth day anguish" has already passed; now enters a more stable phase.',
'Crying now has "intention": he cries differently if he is hungry or bored.',
'It is normal to start putting everything in your mouth; It is their way of knowing the world.',
'Give him leg massages to relax him after a day of lots of kicking.',
'If you use a pacifier, check that it is not worn or cracked.',
'He can now hold a rattle for a few seconds before releasing it.',
'You will notice that the baby "stretches" and loses that fetal position from the beginning.',
'Talking to him about what you\\\\\\\\\\\\\\\'re doing ("Now Daddy\\\\\\\\\\\\\\\'s going to change your diaper") helps his brain.',
'Stroller rides are better if you can see a little more of the landscape (raise the backrest one notch).',
'If you still have a very strong Moro reflex, gentle lulling can help you sleep.',
'Your eye color can begin to change toward your final shade now.',
'He starts laughing out loud; Dad\\\\\\\\\\\\\\\'s funny noises are his best comedy.',
'Don\\\\\\\\\\\\\\\'t wear stiff shoes; Feet need total freedom to develop.',
'Bathing can go from being a procedure to being a time of play with splashes.',
'Take the opportunity to take profile photos; His face changes very quickly in this month.',
'Around this age the “4-month sleep regression” may start; it is a developmental change—be patient.',
'The baby\\\\\\\\\\\\\\\'s brain begins to process sleep like that of an adult (REM and deep phases).',
'He can now turn from his back to his side; Never leave him alone on the changing table.',
'His vision is almost adult-like in terms of focus and color.',
'Focuses on small objects; Be careful with pieces that may fall to the ground.',
'If you hold him by his armpits, he already puts weight on his feet and "jumps."',
'He begins to recognize his name; It will turn around when you call it.',
'Adults\\\\\\\\\\\\\\\' interest in food begins; He will stare at you while you eat.',
'Their periods of vigil (awake) are longer, approximately 1.5 to 2 hours.',
'The games of "peek-a-boo" (covering one\\\\\\\\\\\\\\\'s face) begin to make sense to him.',
'Don\\\\\\\\\\\\\\\'t introduce solids yet; The WHO recommends waiting for 6 months.',
'If he drools a lot and is irritable, cold teethers will be your best allies.',
'You can start to grab your own feet while on your back.',
'Crying out of boredom appears; needs new stimuli every so often.',
'The 4-month vaccines are coming up; ask your pediatrician for the exact date and keep infant paracetamol handy if advised.',
'If you notice a red area on your gum, a tooth is pushing.',
'Toys with simple lights and sounds help him understand cause and effect.',
'Start passing objects from one hand to the other.',
'Your back is stronger; If you feel it with support, it lasts for a while.',
'Daytime sleep usually stabilizes in 3 or 4 light naps.',
'Do not use screens (mobile phone, TV) to distract him; Your brain doesn\\\\\\\\\\\\\\\'t process them well.',
'Change the toy from his hand to encourage laterality.',
'If it is very hot, you can offer the breast or bottle more frequently, but not water.',
'Listening to different languages ​​(songs) at this age is excellent for their brain plasticity.',
'The extrusion reflex (sticking out the tongue) is still present, so you should not eat solids yet.',
'He begins to "scream" with joy; He is testing the power of his lungs.',
'If you bathe him at night, use low lighting so he associates bathing with sleeping.',
'You will notice that he is easily distracted while eating because everything interests him.',
'Put him in front of a safe mirror; You will be fascinated by the "other baby" you see.',
'It is a month of many changes; If you are exhausted, ask for relief. Dad needs rest too.',
'He can now roll over (from face up to face down). Goal accomplished!',
'He is able to distinguish between familiar faces and strangers; you can start to be selective.',
'Its grip strength is surprising; Be careful with your hair or your glasses.',
'He begins to sit with very little support, using his hands as a "tripod."',
'Curiosity is maximum; He will want to touch everything you touch.',
'If you take away a toy from him, he will protest; begins to understand possession.',
'The sounds of farting with the mouth are very funny to him.',
'It can begin to move "crawling" or rotating like the hands of a clock.',
'The baby\\\\\\\\\\\\\\\'s weight has usually doubled since birth.',
'If you offer him a toy, he already extends his arms to take it with clear intention.',
'His hands are open almost all the time, ready for action.',
'He can now hold his own bottle if he drinks formula (although always with supervision).',
'Start to understand the tone of your voice: distinguish if you are happy or if you scold him gently.',
'Carpet games are their main activity; make sure it is clean.',
'It\\\\\\\\\\\\\\\'s a good time to read stories with animal sounds.',
'If he cries at night, try to calm him with your voice before picking him up, so he learns to self-regulate.',
'You will notice that the baby looks at his feet with curiosity, as if they were not his.',
'His digestive system is gradually preparing; complementary feeding comes around 6 completed months.',
'Drooling can cause chin irritation; apply a little protective balm.',
'He begins to "converse" with you, waiting for you to stop talking before making his sound.',
'Natural rubber toys are the best for chewing on now.',
'Don\\\\\\\\\\\\\\\'t leave him in the playpen for too long; need to explore real space.',
'Still no solids yet: the WHO recommends waiting until 6 completed months.',
'The clothing should already be comfortable and elastic so as not to slow down your turning movements.',
'It is normal for him to kick in the bath water until everything is lost.',
'Start following objects that fall to the ground with your eyes.',
'If you have older siblings, this is the month where you start interacting with them the most.',
'The afternoon nap may begin to get shorter.',
'Keep cleaning products and cables out of reach now; It will soon reach them.',
'Practice sitting with support for a few minutes a day; he needs good trunk control before eating.',
'Many babies start to pivot or army-crawl on their tummy; it is not crawling yet, but they move a little.',
'Babbling gets stronger: you will hear single syllables like "ba", "ma" or "da".',
'Offer safe teething toys: they soothe the gums and strengthen hands and mouth.',
'If you take a toy away, the protest will be clearer; he is learning to express what he wants.',
'Cloth or thick board books with textures are ideal for exploring with his hands.',
'Cause-and-effect toys (press and it sounds) help him understand that his actions have results.',
'Do not compare his progress with other babies; motor development is very individual.',
'Practice tummy time several times a day: it strengthens neck, back and arms.',
'He starts sitting with support (cushions or your body); do not leave him sitting alone unsupervised.',
'Dropping a toy so you pick it up teaches gravity… and patience to parents.',
'Sleep may become irregular if he is practicing rolling or sitting.',
'Milk (breast or formula) is still his only food; he does not need yogurt or other cow’s milk products yet.',
'With music he will move arms and trunk with enthusiasm: that is his way of “dancing”.',
'As he moves more, check the crib: firm mattress, no loose objects or pillows.',
'He will stare while you eat; interest in food often appears weeks before tasting it.',
'6 months are almost here: learn about complementary feeding and safe cuts (BLW or purées).',
'Drooling and tender gums are common; a gentle massage with your clean finger can help.',
'Full crawling is still early for most; if he only rolls or pivots, that is perfectly on track.',
'With support he can sit for a while and try to play with his hands.',
'Put a toy a little out of reach on the mat: he will practice turning and reaching without being forced to crawl.',
'If you are unsure when to start solids, ask your pediatrician; the usual reference is 6 completed months.',
'He tells familiar faces apart better; he may get serious or uneasy with new people.',
'If he fusses when left in someone else’s arms, that is healthy attachment: say goodbye calmly and come back.',
'Rattles and easy-to-grasp objects are still excellent for hand-eye coordination.',
'Barefoot at home whenever you can: he needs to feel surfaces and move his feet freely.',
'Do not start complementary feeding early without medical advice; his digestion is still maturing.',
'His grasp improves: he holds toys more firmly and brings them to his mouth to explore.',
'Everything goes in the mouth: keep coins, magnets, batteries and small objects out of reach.',
'Imitate his sounds and gestures; it is one of the best ways to boost language now.',
'Congratulations! You are about to reach the great milestone of 6 months.',
'The WHO recommends starting complementary feeding now, keeping milk as the main food.',
'If you opt for Baby Led Weaning (BLW), make sure the pieces are soft and long.',
'Don\\\\\\\\\\\\\\\'t add salt or sugar to your meals; His kidneys are not prepared and he does not need them.',
'Half a year of life! It\\\\\\\'s a great time for a celebratory family photo.',
'It is normal that at first he only plays with his food and hardly swallows anything.',
'Many babies can sit with little support or alone; if he still needs help, practice calmly.',
'Water is offered for the first time with meals, preferably in a learning glass.',
'The grill or egg must always be very well cooked to avoid risks.',
'Poop will change smell, color and consistency radically with solid food.',
'It\\\\\\\\\\\\\\\'s time to buy a high chair that\\\\\\\\\\\\\\\'s safe and easy to clean (you\\\\\\\\\\\\\\\'re going to be cleaning a lot).',
'Cereals don\\\\\\\\\\\\\\\'t have to be from a box; rice, oats or natural corn are better.',
'Give him his own spoon while you give him another; he loves to imitate.',
'Honey is strictly prohibited before the year due to the risk of botulism.',
'Iron is vital now; Prioritize foods such as legumes, meat or whole grains.',
'Don\\\\\\\\\\\\\\\'t force the baby to eat; He knows when he is full. Respect their signals.',
'Bathing after eating can be a good strategy to clean up the mess.',
'He will begin to pass objects from one hand to the other with complete fluidity.',
'Their naps may start to become more predictable: one mid-morning and another after eating.',
'He can now distinguish tones of voice: he knows perfectly well when you are joking.',
'Play hide objects under a blanket; will start looking for them.',
'Drooling may intensify if the first lower incisors are about to emerge.',
'If you give purees, try not to always make them a liquid mixture; leaves some lumps.',
'White fish can be introduced now; always watch the thorns.',
'It\\\\\\\\\\\\\\\'s a good time to take it shopping; The colors of the market fascinate him.',
'Don\\\\\\\\\\\\\\\'t use screens to make him eat; You must be aware of food and its satiety.',
'If he chokes a little (gagging), stay calm; It is your reflection of security acting.',
'Whole nuts are prohibited due to the risk of suffocation up to 5 years of age (they can be ground).',
'He may start using his index finger more to point or explore details; it is still early days.',
'You will notice that he already has a very marked "personality" in his tastes.',
'A mirror at his height in the play area will help him recognize himself.',
'"Separation anxiety" may appear: he cries if he loses sight of you for a second.',
'This fear is a sign of intelligence: it already knows that you are unique and that you can leave.',
'Play peek-a-boo a lot so he understands that even if he doesn\\\\\\\\\\\\\\\'t see you, you always come back.',
'Start doing the "pincer" (picking things up with your thumb and index finger).',
'His curiosity about plugs increases; It is vital that they are protected.',
'You can now eat more chopped or mashed foods with a fork.',
'He loves to imitate animal sounds; the dog and the cow are the classics.',
'If you try to stand up using furniture, be careful not to let it fall on you.',
'Legumes are great for your diet; Give them well cooked and mashed.',
'His short-term memory improves: he remembers where you keep his toys.',
'It is normal to reject foods that you previously liked; Don\\\\\\\\\\\\\\\'t give up, try again.',
'Bath time may be longer now that he enjoys playing with water.',
'Some babies start pointing at what they want; if not yet, it will come in the next months.',
'Don\\\\\\\\\\\\\\\'t use your phone in front of him as a distraction; prefers your real interaction.',
'If he crawls, make sure there are no coins or small pieces on the floor.',
'Begin to understand the concept of "in" and "out" (putting blocks in a cube).',
'Your receptive vocabulary (what you understand) is much larger than your expressive one.',
'Dinners should be light so that they do not interfere with your night\\\\\\\\\\\\\\\'s rest.',
'If you have mosquitoes, washing your nose before bed will help you rest better.',
'Let him experiment with the spoon even if he ends up with food in his hair.',
'You can now drink small amounts of water from a regular bottle or glass with assistance.',
'The chewing reflex is very active even if it does not have many teeth.',
'Begins to show clear preferences for certain toys or stuffed animals.',
'"Claps" games help your coordination and rhythm.',
'You\\\\\\\\\\\\\\\'ll notice him turn around immediately when he hears a familiar sound outside the room.',
'If he sleeps in his room, a baby monitor will give you peace of mind during this stage of movement.',
'It\\\\\\\\\\\\\\\'s a good time to start setting soft boundaries ("don\\\\\\\\\\\\\\\'t touch that").',
'Always clean hands; Now that it explores the soil, the risk of viruses increases.',
'Direct sun is still dangerous; Always look for shade on walks.',
'Praise their achievements; Your positive reaction is their greatest motivation to learn.',
'Many babies already stand up on their own, leaning on the couch or your legs.',
'He will begin to take "side steps" while holding on to furniture (cruising).',
'He perfectly understands the word "No", although sometimes he decides to ignore it.',
'He is fascinated by books with flaps that he can lift himself.',
'He is able to hold an object in each hand and hit them together to make noise.',
'Their diet is already very similar to that of adults, only without salt or spicy foods.',
'If he crawls quickly, be prepared to chase him around the house.',
'Start dropping objects on purpose to see how they fall and what noise they make.',
'Communication is more two-way; wait for your response after making a sound.',
'He is capable of finding a toy that you have completely hidden in front of him.',
'Naps can be reduced to two very clear and stable ones.',
'Do not give foods with small round shapes (whole grapes, cherry tomatoes) without cutting them.',
'His dexterity with the digital clamp allows him to pick up even a crumb of bread.',
'He will start trying to "help" you when you dress him, putting his arm through the sleeve.',
'Cause-effect games (press a button and make something sound) obsess him.',
'You will notice that the baby has "attachment" to a specific object (blanket or stuffed animal) to sleep.',
'If he babbles a lot, try to "translate": "Do you want the red car?"',
'It is a good time to introduce teeth cleaning routines with a very soft brush.',
'Be careful with the tablecloths; If you pull on them, whatever is on top will fall on top of you.',
'Crawling strengthens the muscles you will later use for writing and eating.',
'He starts to recognize specific songs and can try doing the gestures.',
'If it falls (and it will fall), don\\\\\\\\\\\\\\\'t panic; Your calmness helps him evaluate if it really hurts.',
'You can now eat pasta in small shapes or cut up to practice grip.',
'His curiosity about the food on your plate is the best way to get him to try new things.',
'Changing his diaper becomes a challenge because he doesn\\\\\\\\\\\\\\\'t want to sit still; have a toy on hand.',
'Begins to understand spatial concepts such as "up" and "down."',
'His laugh is contagious; gentle tickling games work wonders.',
'If you go out to dinner, bring toys that don\\\\\\\\\\\\\\\'t make a lot of noise to keep him entertained.',
'The relationship with other children is based on observation; He looks at them with great attention.',
'We\\\\\\\\\\\\\\\'re almost into the year! Your baby has grown and learned more in these 9 months than in the rest of his life.',
'It is very likely that he already moves around the house leaning on the furniture ("cruising").',
'He starts to understand simple requests (“get the toy”); two-step ones will come later.',
'He loves to put things in and out of boxes or drawers; It is an excellent exercise in logic.',
'If he already stands up, check that there are no heavy objects on tablecloths that he could pull down.',
'His gestural language is key: he will say "no" with his head before knowing how to say it with his mouth.',
'He can now eat almost anything, including whole legumes (well cooked) and pieces of tender meat.',
'The game of hide-and-seek (you hide and he looks for you) generates a lot of laughter and anticipation.',
'He begins to show interest in using the comb or toothbrush on his own.',
'Curiosity about cables is maximum; Use gutters to hide those from the TV or router.',
'He may begin to have "tantrums" of frustration when something doesn\\\\\\\\\\\\\\\'t go his way.',
'He is able to bend down to pick up something from the floor while holding onto a piece of furniture.',
'Their babbling starts to sound like "real conversation" even though you don\\\\\\\\\\\\\\\'t understand the words.',
'Books with real sounds (animals, cars) are his weakness this month.',
'If he tries to climb stairs, always let him do it under your supervision so he can learn.',
'You already recognize the characters from your favorite stories; Point them out and let them look for them.',
'Start imitating household tasks: "wiping" with a rag or trying to sweep.',
'The morning nap may begin to be shorter or disappear in some babies.',
'Don\\\\\\\\\\\\\\\'t give him choking-risk foods like popcorn or candy.',
'Promotes their autonomy by letting them choose between two fruit options for snacking.',
'Your hands are already strong enough to open some types of simple zippers.',
'Crawling is still the best exercise for your brain development and coordination.',
'If he cries at night, it may be due to delayed "separation anxiety"; A kiss and calm will be enough.',
'He is able to point out parts of his body if you repeat them often (where is the eye?).',
'Building games with large blocks help their spatial vision.',
'He can now drink from a normal glass if you hold him; Practice flow control.',
'Begins to show preferences for certain colors of clothing or toys.',
'If you have a dog or cat, make sure the baby is not too rough with them; He is learning empathy.',
'You will notice that he becomes more "clown" to get your attention and make you laugh.',
'Hand hygiene is vital now that you touch absolutely everything on the floor.',
'10 months! His fine motor skills already allow him to pick up very small objects with great precision.',
'He may try to let go of the furniture and stand for just a few seconds.',
'Their meaningful "first words" usually appear now (water, bread, dog).',
'The concept of "property" appears: "mine" will be one of your main ideas soon.',
'He loves it when you read him the same story over and over again; Repetition is how they learn.',
'You can now use a spoon with some effectiveness, even if half of it ends up outside.',
'He begins to understand the concept of "waiting" for a moment, even if it costs him a lot.',
'Pull toys (animals with wheels and rope) are ideal for this stage.',
'If he takes his first steps alone, don\\\\\\\\\\\\\\\'t force him; your brain will decide when it feels safe.',
'Curiosity about the contents of kitchen cabinets is endless; Leave one with safe things (tapers).',
'You may start to be afraid of loud noises like the vacuum cleaner or dryer.',
'You will notice that the baby has much more physical resistance and gets less tired on walks.',
'He is able to obey simple commands such as "Don\\\\\\\\\\\\\\\'t touch that!" (although I tried again after 2 minutes).',
'Play with other babies remains "parallel": they play close but not together.',
'Scribbling with thick crayons may appear; if he is not interested yet, there is no rush.',
'You no longer need purees at all; He can eat the same thing as you, cut small.',
'Start identifying moods on your face: know if you are sad or happy.',
'The coordination to throw a ball (although without much aim) is already there.',
'If you travel by car, make sure the seat is still suitable for your weight and height.',
'He loves seeing photos of himself and the family on your phone or in albums.',
'He is able to recognize songs by the initial melody and start clapping.',
'If he crawls, his knees may be a little red; It\\\\\\\\\\\\\\\'s normal, your skin is tanning.',
'Don\\\\\\\\\\\\\\\'t put him in shoes with stiff soles yet; Flexibility is key for the arch of the foot.',
'You can now use your index finger to point to something that is far away (a bird, a plane).',
'He begins to understand that objects serve something: the hair comb, the telephone to the ear.',
'If he gets very frustrated with a toy, teach him to ask for help instead of crying.',
'Mealtime is a social event; integrate it at the table with the rest of the family.',
'It is normal to eat less than before; its growth is slowing.',
'Water games (filling and emptying glasses) are his favorite activity in the bathroom.',
'He begins to show a sense of humor; will do "forbidden" things just to see your reaction.',
'Only one month left until the first birthday! Start planning something simple.',
'He\\\\\\\\\\\\\\\'s already starting to point his finger to ask for things. Validate your communicative intention by always saying the name of what you are pointing out.',
'Until 12 months, the main milk remains breast milk or formula; cow’s milk should not replace it yet.',
'Honey remains forbidden until 12 months due to botulism risk; do not use even small amounts.',
'Many babies take their first independent steps around this time.',
'Their vocabulary usually has between 2 and 5 words with real meaning.',
'You can now start wearing shoes with a slightly firmer sole to go outside.',
'The transition from bottle to cup should be almost complete now to protect their teeth.',
'He is able to follow the rhythm of a song by clapping or tapping softly.',
'His curiosity about food is maximum; Take advantage to introduce more complex flavors.',
'The "crisis of the year" can bring changes in sleep or appetite; It is transitory.',
'He already knows how to wave "goodbye" spontaneously when someone leaves.',
'You can start using cutlery (blunt fork) with some skill.',
'He loves to help pick up his toys if you turn it into a game with music.',
'Their naps are normally consolidated into a single long one after eating.',
'Begins to understand space concepts: "inside the box", "under the table".',
'He is able to recognize himself perfectly in the mirror and make faces.',
'Pretend play begins: you can have him "drink" from an empty toy cup.',
'If you are still breastfeeding, go ahead! La OMS recomienda seguir hasta los 2 años o más.',
'Their weight is usually triple what they were at birth and their height has grown by 50%.',
'He begins to show a clear preference for one of the two parents depending on the activity.',
'It is time for the 12-month check-up and its corresponding vaccines.',
'You can now eat whole eggs (white and yolk) without fear of allergies if you have not shown them.',
'He is fascinated by "chase" games: crawling after him or having him chase you.',
'Your attention span is greater; You can spend 5-10 minutes focused on a toy.',
'Start trying to climb onto the couch or chairs; Always watch your back.',
'Kisses and hugs begin to be more "intentional" and affectionate.',
'Don\\\\\\\\\\\\\\\'t get overwhelmed with the birthday party; The baby will become overwhelmed if there are too many people and noise.',
'Routines remain your security anchor; Try to maintain sleep schedules.',
'Start using your finger to press buttons very precisely.',
'Congratulations, dads! You have successfully survived the first year of breeding.',
'No longer a "baby", he is now a little boy with a lot of his own will.',
'If you already walk, your balance will improve every day; Falls are part of learning.',
'He\\\\\\\\\\\\\\\'s starting to understand the concept of "waiting" a little better, although it\\\\\\\\\\\\\\\'s still difficult.',
'Their communication is a very effective mixture of words, gestures and sounds.',
'He loves to "read" his own stories by turning the pages one by one (even if they are cardboard).',
'From one year on, honey is safe in moderation; keep prioritizing real food over sugar.',
'Playing with sand or dirt in the park is an incredible sensory experience for him.',
'He starts trying to take off his socks or shoes on his own.',
'His tantrums may be more frequent because his mind is faster than his language.',
'He is able to identify the animals in the drawings and make their sounds.',
'If you introduce whole cow’s milk, treat it as one more food, not the diet base; prioritize solid food.',
'He begins to show interest in pencils and tries to make lines on the paper.',
'If you ask him for something, he can go look for it in another room and bring it to you.',
'He loves zipper closures and big buttons; let him practice.',
'His personality is becoming clearer: is he observant, active, calm or restless?',
'You can now drink with a straw; It is an excellent exercise for the muscles of the face.',
'Begin to understand the concept of "sequence": first the bath, then the pajamas.',
'Games of fitting geometric figures (circle, square) are starting to work out well for him.',
'He loves that you take him by the hand to walk down the street.',
'His curiosity about "what\\\\\\\\\\\\\\\'s inside" things will lead him to try to disassemble toys.',
'He is able to point out three or four parts of his body with precision.',
'Begins to imitate complex adult gestures, such as pretending to talk on the phone.',
'You will notice that he begins to have favorite "friends" in the park.',
'Its receptive vocabulary is enormous: it understands almost everything you say in context.',
'Bedtime can become a bit of a “negotiation”; hold the line lovingly.',
'He can now eat fruit with skin (well washed) if it is thin and he has teeth.',
'He loves to climb up and down small things; The park steps are a challenge.',
'Begins to show interest in clothes; You can point out the shoes you want to wear.',
'The use of "No" becomes their favorite tool to mark their independence.',
'Enjoy this stage: your baby is now a little adventure companion.',
'If he already walks easily, he will begin to try to carry heavy objects from one side to the other at the same time.',
'He loves to put keys in locks or coins in slots; Its accuracy improves every day.',
'He is able to turn the pages of a book one by one, although sometimes he skips some.',
'He begins to identify objects by their use: "bring me the shoe" and he will know what to look for.',
'Building games are now more about "destruction": it\\\\\\\\\\\\\\\'s more fun to knock down your tower than to make it.',
'You will notice that he begins to eat more cleanly, although he still uses his hands for what he misses.',
'It\\\\\\\\\\\\\\\'s a great time to introduce push toys (like toy shopping carts).',
'You can now understand the difference between "inside" and "outside" clearly.',
'Your receptive vocabulary is like a sponge; Avoid saying words you don\\\\\\\\\\\\\\\'t want them to repeat.',
'He begins to show interest in real animals; If you have a pet, teach him to pet it "gently."',
'He can now drink from a glass without a spout if you help him hold it.',
'He loves it when you chase him around the house; Their laughter will tell you that it is their top game.',
'Start imitating self-care gestures, such as trying to wash your face with a sponge.',
'The afternoon nap becomes sacred; If you skip it, the afternoon will be "complicated."',
'Is able to scribble circles or lines with colored crayons; large paper on the floor is ideal.',
'He can now point to 5 or 6 parts of his body accurately.',
'You will notice that he begins to have "hand preference" (right or left-handed), although it can change.',
'Toys with small wheels (cars) are fascinating to him now.',
'He begins to understand that the photos on his cell phone represent real people he knows.',
'Your balance improves so much that you can try dancing around (and get a little dizzy).',
'He is able to follow single-step instructions without gestural support.',
'He starts to "help" you pick up the clothes from the washing machine; He loves to feel useful.',
'His curiosity about what is "upstairs" will lead him to try to climb through the drawers.',
'Bath time is a field of experiments: what floats and what sinks?',
'He begins to be shy around strangers, even people he has met before.',
'You can now eat larger pieces of fruit; His jaw is much stronger.',
'He loves opening and closing doors; Put protectors so your fingers don\\\\\\\\\\\\\\\'t get caught.',
'Start using words to express basic needs (more, water, bread).',
'Ball games are great for your foot-eye coordination.',
'Disorder is their way of learning physics. If he throws food on the floor or hits two toys, he\\\\\\\\\\\\\\\'s not being "bad"; It is testing the gravity and acoustics of its environment.',
'The first selective tastes appear: you may only want to eat things of a specific color.',
'He will begin to use complex gestures, such as leading you by the hand towards what he wants.',
'It is able to recognize your name even if there is background noise or you are far away.',
'Wooden puzzles with large pieces (fit together) are starting to be a piece of cake.',
'You can now walk back a few steps; It is an important milestone of balance.',
'Their attention span in a story increases after 10-15 minutes if there are striking drawings.',
'You begin to understand the concept of "waiting" a little better (just a little).',
'He loves to hide things in strange places (shoes, flower pots); Check before leaving home.',
'He can now climb stairs crawling or holding his hand very safely.',
'Milk is still important, but your diet should already be 100% varied.',
'He will begin to imitate complex tasks: "sweeping", "talking on the phone" or "cooking".',
'His sense of humor becomes more sophisticated; He will do stupid things to make you laugh.',
'It is able to identify family members in group photos.',
'Games with other children are still "in parallel", but they look at each other much more.',
'You will notice that he begins to have a "comfort" toy that he wants to carry everywhere.',
'You can now use the fork to pierce soft pieces of food.',
'He starts to show frustration if you don\\\\\\\\\\\\\\\'t understand what he is trying to tell you.',
'He is fascinated by books that have sounds of nature or the city.',
'It is the ideal time to start teaching him to wash his hands alone.',
'His ability to climb onto the couch is now an expert skill; maximum vigilance.',
'Begins to understand negative phrases ("there is no more", "it can\\\\\\\\\\\\\\\'t be done").',
'Routines give him the peace he needs to not have so many tantrums.',
'He loves to play with empty cardboard boxes; sometimes they are better than the toy that came inside.',
'He can now throw a ball with his hands forward in a certain direction.',
'Begin to identify sounds from outside (an ambulance, a barking dog).',
'Their sleep can be disrupted by motor milestones: sometimes they "practice" in their sleep.',
'He is able to point out a bird in the sky or a dog in the distance.',
'Don\\\\\\\\\\\\\\\'t use "no" for everything; reserve that word for real dangers.',
'He begins to show interest in adults\\\\\\\\\\\\\\\' shoes and will try to put them on.',
'15 months! Their independence grows and so does their speed.',
'The spoken vocabulary usually grows suddenly: it can have between 10 and 20 clear words.',
'Begin to understand opposite concepts: big/small, cold/hot.',
'He can now run, although his way of doing it is a little "clumsy" and with his arms open.',
'He loves when you sing choreographed songs to him (like "Cinco lobitos" or "El patio de mi casa").',
'He is able to stack 3 or 4 blocks without them falling.',
'He will begin to use his own spoon much more precisely towards his mouth.',
'His curiosity about the human body increases: he will point out the nose, mouth and eyes.',
'He can now distinguish perfectly between what is food and what is not (even if he tries everything).',
'He is fascinated by watching other older children play; learn by pure observation.',
'Start having a "favorite song" that you\\\\\\\\\\\\\\\'ll ask for over and over again.',
'He is able to recognize objects in books even if they are abstract drawings.',
'You will notice that it has much more strength to push chairs or move small furniture.',
'You can now safely go down stairs sitting or on your back.',
'He begins to show interest in "helping" set the table (things he doesn\\\\\\\\\\\\\\\'t break).',
'Its imitation capacity is so high that it will repeat your gestures when you are angry or happy.',
'It is normal to have days of acute "mastitis" or "papitis"; you need to recharge your security.',
'Sand games allow you to practice fine motor skills (filling buckets).',
'He begins to understand that things have a place: "put this away."',
'You can now identify animals by the sound they make without seeing them.',
'His independence when eating makes him reject you giving him food.',
'He is able to scribble with more intention, trying not to leave the paper.',
'You will notice that his laugh is much more social and seeks accomplices.',
'He begins to show empathy: if he sees another child crying, he may become sad or look at him with concern.',
'You can now drink with a straw with complete control.',
'He loves to pretend he is an animal (crawl like a cat, roar like a lion).',
'His curiosity about nature is infinite: an ant on the ground is a spectacle.',
'He begins to understand the concept of "mine" very strongly.',
'You can now remove simple clothing such as your hat or socks.',
'Fears may begin to appear (darkness, shadows); always validate them.',
'Your baby is now a little explorer eager to take on the world!',
'We enter the "I alone" phase: he will want to do everything without your help even if it takes three times as long.',
'His balance is so good that he can try to kick a ball without falling.',
'Begins to understand instructions that involve two related steps ("pick up the story and put it on the table").',
'He loves to dance to rhythmic music; You will move your entire body, not just your arms.',
'He can already identify basic colors if you repeat them often during games.',
'Their vocabulary is enriched with simple adjectives (dirty, rich, ugly).',
'He begins to have a notion of ownership: he knows which shoes are dad\\\\\\\\\\\\\\\'s and which are mom\\\\\\\\\\\\\\\'s.',
'He is able to climb onto a small chair and sit properly on his own.',
'You will notice that the child has longer periods of concentrated play (up to 20 minutes).',
'He can now eat almost any texture, but always cut very hard things.',
'He is fascinated by "cleaning" glass or mirrors; Give him a dry cloth and he will have a lot of fun.',
'He begins to use the pronoun "I" or his own name to refer to himself.',
'His skill with Velcro closures is total; He will take off his shoes at the least opportune moment.',
'He loves playing "Santa Claus" games or hiding small gifts.',
'You can now distinguish between a real dog and a stuffed dog.',
'He begins to show interest in going to the bathroom when you go; It is the beginning of curiosity about the urinal.',
'He is able to recognize children\\\\\\\\\\\\\\\'s songs by the first two notes.',
'His strength to throw objects is greater; Teach him that "things are not thrown away."',
'You will notice that he really likes repetition: same story, same food, same route to the park.',
'He can now jump down from a very low step (with help).',
'He begins to understand the concept of "tomorrow" or "after", although his notion of time is limited.',
'He loves playing with play dough (make sure he doesn\\\\\\\\\\\\\\\'t eat it); It\\\\\\\\\\\\\\\'s great for your fingers.',
'Your gestural communication becomes very sophisticated to ask for what you want.',
'You can now open some simple screw-top jars; Be careful what\\\\\\\\\\\\\\\'s inside.',
'You begin to show a preference for certain TV programs or short videos; limits its use.',
'He is able to identify sounds in the house: the doorbell, the microwave, running water.',
'Their ability to climb is now their greatest danger; Check the stability of the shelves.',
'He loves it when you read him bedtime stories; It is his favorite moment of calm.',
'You can now start using the toothbrush with a little paste (grain size of rice).',
'Your child is now a mirror in real time. If you want him to learn to say hello, say thank you, or try a new food, make sure he sees you doing it first.',
'At 17 months, "I alone" begins to be the law. Even if you are in a hurry to leave the house, try to give him 2 minutes to try to put on a shoe or climb a step without help.',
'Many children have the "language explosion" this month: they learn new words every day.',
'You can start putting two words together to form short sentences ("more water", "dad shut up").',
'He now walks with complete confidence, even quickly or trying to jog.',
'His ability to imitate domestic actions is total: he will want to "cook" or "iron" like you.',
'He is able to climb stairs standing up holding onto the railing or your hand.',
'Games of fitting together complex pieces are already a fun challenge for him.',
'He begins to show interest in other children and may try to share a toy (even if it costs him).',
'You can now use a spoon and fork quite cleanly.',
'His personality is overwhelming; He has very defined tastes and defends them.',
'Is able to identify 10 or more common objects in a book.',
'You will notice that you begin to have less need for long naps, although one a day is still vital.',
'You can now wash your hands and face with a little help.',
'He loves playing with water: filling buckets, watering plants or just splashing around.',
'He begins to understand the concept of "helping" in a real way: "bring the dirty diaper."',
'Your long-term memory capacity increases: remember where you were yesterday.',
'He can now kick a moving ball without losing his balance.',
'He begins to show curiosity about genitals and the differences between boys and girls.',
'He is able to use the potty occasionally if you invite him, although he is not yet in control.',
'"Search and find" books are ideal for this stage of visual acuity.',
'You will notice that the child has much more willpower: "no" is his power word.',
'You can now take off simple clothing items (rubber pants, shoes).',
'He begins to show interest in colored pencils and tries to "color" drawings.',
'His sense of balance allows him to walk on uneven surfaces (grass, sand).',
'He is able to understand complex negative instructions ("don\\\\\\\\\\\\\\\'t touch that burning thing").',
'He loves playing with soap bubbles; will try to catch them and blow them away.',
'His communication with other adults (grandparents, uncles) is much more fluid.',
'He can now get on and off the sofa or his dining chair without help.',
'He begins to show pride when he accomplishes something difficult ("Look, Dad!").',
'18 months! You\\\\\\\\\\\\\\\'re three-quarters of the way to 2 years old.',
'At 18 months, his balance lets him climb stairs alternating feet if you hold his hand.',
'Start using adjectives to describe things: "big," "dirty," "cold."',
'He loves to help with real tasks: "take this to the trash" or "bring your shoes."',
'You can now complete 3 or 4 piece lace puzzles with ease.',
'His symbolic game is more complex: he now "talks" on the phone to imaginary people.',
'He perfectly identifies objects by their function: "what do we comb our hair with?"',
'You will notice that he begins to have a more marked "hand preference", although he can still alternate.',
'He can now run around obstacles without falling as much.',
'He loves playing with other children, although "sharing" remains an emotional challenge.',
'Begin to understand quantity concepts such as "one" or "many."',
'He can already identify 5 or 6 colors if you repeat them often.',
'His curiosity about animals increases; identifies sounds of wild animals in books.',
'He can now jump with both feet together from a very low step.',
'He begins to show a preference for certain specific bedtime stories.',
'He loves playing with plasticine; It stimulates their fine motor skills and imagination.',
'He is able to recognize his clothes and knows who owns each item at home.',
'You will notice that he begins to have a "best friend" or favorite companion in the park.',
'You can now use the fork with ease to pierce foods of different hardness.',
'He begins to understand the concept of "turn" in the game, although he needs some guidance.',
'He loves it when you tell him what you do: "Now dad is making dinner."',
'It is capable of imitating engine sounds: cars, airplanes or the blender.',
'You can now open doors with a crank; Check your home security locks.',
'He begins to show interest in colored pencils; his scribbles are already circular in shape.',
'Your memory capacity allows you to remember where you kept a toy yesterday.',
'He can now drink from a regular cup with one hand (with supervision).',
'He is fascinated by classifying objects by size: from largest to smallest.',
'He begins to use the pronoun "I" to refer to himself.',
'He is able to follow two-step instructions: "Pick up the toy and put it in the box."',
'Your sense of rhythm improves: you can follow a song by tapping your foot.',
'19 months! Your baby already has the energy of a tireless little explorer.',
'At 19 months, his vocabulary often has an “explosion” of new words each week.',
'He can now bend down to pick up something and stand up without losing his balance.',
'He starts showing interest in brushing his teeth "only" after you do.',
'He loves to play dress-up: putting on adult hats, glasses or shoes.',
'He is able to identify family members in old or digital photos with joy.',
'He can now kick a moving ball without falling.',
'He begins to express his basic emotions with words: "happy", "sad", "scared".',
'He loves playing with water: filling and emptying containers teaches him about volume.',
'His ability to climb onto the couch is now an expert skill; watch for falls.',
'He can now use the spoon without dropping almost any food.',
'Begin to understand the concept of “inside,” “outside,” “up,” and “down” precisely.',
'He loves to imitate the noises in the house: the vacuum cleaner, the doorbell or the microwave.',
'He can now walk on tiptoe for a few seconds if he plays with you.',
'He is able to recognize children\\\\\\\\\\\\\\\'s songs only by the first seconds of melody.',
'Start showing empathy: if he sees you "sad", he may try to give you a kiss or a toy.',
'He can now take off simple items of clothing (sweatpants) without help.',
'He is fascinated by the game of "hide and seek" with objects; You look for it and let it find it.',
'His curiosity about soil bugs is endless; Make sure he doesn\\\\\\\\\\\\\\\'t eat them.',
'He can now start using the potty occasionally if he shows interest.',
'He begins to have a notion of ownership: "that\\\\\\\\\\\\\\\'s dad\\\\\\\\\\\\\\\'s," "that\\\\\\\\\\\\\\\'s baby\\\\\\\\\\\\\\\'s."',
'He is able to stack 5 or 6 blocks without the tower collapsing.',
'He loves to help "sweep" or "wipe" dust with a dry rag.',
'He can now identify animals by their shadow or silhouette in books.',
'His gestural communication is combined with words to make himself understood better.',
'He begins to show interest in "grown-up" food with more complex textures.',
'It is capable of opening large zippers on backpacks or jackets.',
'He is fascinated by seeing photos of himself as a newborn.',
'He can now jump from a small height, landing with both feet.',
'He begins to understand the concept of "after": "after nap we will go to the park."',
'20 months! His personality shines brighter every day.',
'At 20 months, he already identifies primary colors quite successfully.',
'Begin to form simple two-word sentences: "more bread", "dad shut up".',
'He loves to play with sand; Filling buckets and making "cakes" improves their motor skills.',
'You can now open non-safety screw-top jars.',
'Its balance allows it to walk on uneven surfaces such as grass.',
'Begins to show interest in puzzles with geometric shapes (circle, triangle).',
'He is able to recognize street sounds: an ambulance, a motorcycle, a bird.',
'You can now wash your hands and face with a little supervision.',
'He loves to "read" his favorite stories to his dolls or stuffed animals.',
'He begins to use the pronoun "mine" with great authority; He is marking his space.',
'He can now climb stairs using only one hand on the wall.',
'It is able to identify which object is missing if you hide one of a group of three.',
'He loves helping take clean clothes out of the washer and put them in the hamper.',
'His curiosity about dad\\\\\\\\\\\\\\\'s tools (screwdrivers, wrenches) is maximum; use toys.',
'He can now eat with a fork and spoon, alternating them depending on the food.',
'He begins to understand the concept of "stop" immediately when you ask him to.',
'He loves playing with soap bubbles and trying to catch them without breaking them.',
'He is able to scribble vertical and horizontal lines with intention.',
'You can now distinguish between "cold" (ice) and "hot" (food) with confidence.',
'He begins to show pride in his achievements: "look dad, look!"',
'His long-term memory allows him to remember the names of children he rarely sees.',
'He can now take off his Velcro shoes on his own as soon as he gets home.',
'He loves to play with cardboard boxes; They can be a car, a boat or a cave.',
'He begins to understand that actions have consequences: "if you throw the water, the ground will get wet."',
'He is able to recognize the brands of his favorite foods in the supermarket.',
'He can now drink from a small bottle with a sports mouthpiece without help.',
'He is fascinated by imitating the gestures you make when you talk on your cell phone.',
'His coordination allows him to start pedaling a tricycle (although it is difficult for him to move forward).',
'He begins to show interest in books that have hidden flaps or textures.',
'21 months! A small engine of curiosity that doesn\\\\\\\\\\\\\\\'t stop for even a second.',
'At 21 months, tantrums can be intense because he already knows exactly what he wants.',
'Starts using other people\\\\\\\\\\\\\\\'s names to get their attention.',
'He loves to pretend to be an animal: roar like a lion or jump like a rabbit.',
'You can now identify 3 or 4 less common body parts (knee, elbow, chin).',
'He is able to stack up to 8 blocks in a tower before it falls.',
'He begins to show interest in "coloring" drawings, although he still goes out a lot.',
'You can now open doors that do not have a knob (by pushing or pulling).',
'He loves playing with the ball: throwing it, kicking it and chasing it non-stop.',
'Your attention span on an activity goes up to 20 minutes if you like it.',
'You can now identify what clothes you put on each part of your body.',
'He begins to use "No" not only as a rejection, but as an affirmation of his will.',
'He is able to recognize the way to the park or grandparents\\\\\\\\\\\\\\\' house.',
'He loves to help water the plants with a small toy watering can.',
'He can now walk down stairs standing up if he holds on with both hands.',
'Begins to show more specific fears (a large dog, a noise of thunder).',
'He is able to identify objects by their smell if they are very characteristic (lemon, soap).',
'He loves playing with Lego-type constructions with large pieces (Duplo).',
'You can now eat whole fruit (apple, pear) with skin if it is well washed.',
'Begin to understand the concept of "sharing" a toy for a short time.',
'Its receptive vocabulary is almost complete: it understands almost everything you say in context.',
'He can now brush his teeth with very little help, although you will have to brush them later.',
'He loves it when you sing him songs that involve hand gestures.',
'He is able to identify the characters in his favorite cartoons by their voice.',
'He can now run safely and brake suddenly without falling on his face.',
'He begins to show interest in the origin of things: "where does this come from?"',
'His hand-eye coordination allows him to string large beads on a cord.',
'He loves to "cook" with his toys while you make the real food.',
'He can now climb a small slide and jump down sitting down without fear.',
'He begins to show preferences for the color of his toys or clothes.',
'22 months! Your emotional world is increasingly richer and more complex.',
'At 22 months, his communication is a very effective mix of words and gestures.',
'He can now jump forward with both feet, like a little frog.',
'He begins to show a lot of interest in the potty; It is time for the first tests.',
'He loves to help set the table with light things (napkins, bread).',
'He is able to complete 6-piece puzzles if you help him a little at first.',
'You can now identify which objects are for the bathroom, kitchen or bedroom.',
'His curiosity about how things work leads him to try to "fix" toys.',
'Start using three-word phrases: "Dad, I want water."',
'He loves playing with clay or sensory dough; Dirt is learning.',
'He can now walk backwards and sideways with complete safety.',
'He is able to recognize letters or numbers if you have taught them as a game.',
'You start to understand the concept of "waiting" a little better (up to 2 or 3 minutes).',
'He loves when you read him long stories with a simple plot.',
'You can now open and close plastic jars with snap lids.',
'His coordination allows him to start kicking a ball towards an objective (goal).',
'He begins to show interest in personal hygiene: "my hands are dirty."',
'He is able to identify animals by their basic habitat (in water, in the field).',
'He can now get on and off the sofa or small bed without any help.',
'He loves to imitate the gestures of his older siblings or other children.',
'His sense of balance is so good that he can try walking on a low curb.',
'Start using adverbs of place: "here", "there", "above", "far away".',
'You can now use children\\\\\\\\\\\\\\\'s plastic scissors (with supervision) to make fringes.',
'He loves to play "little meals" and offer you what he has prepared.',
'It is able to recognize the logo of your favorite store or restaurant on the street.',
'He can now put on his coat on his own if you hold his sleeves at first.',
'He begins to show preferences for the order of his things: "this goes here."',
'His memory allows him to remember entire songs and hum them.',
'He is fascinated by how machines work: the garbage truck is his hero.',
'You can now identify which objects are "dangerous" because they burn or cut.',
'Your little one is already beginning to understand temporal sequences. Use "first this, then that."',
'Apply the "Power of Limited Choice." If he refuses to collaborate, do not impose; offers two valid options: "Do you want to brush your teeth before or after your pajamas?"',
'Their vocabulary usually already has between 50 and 200 words depending on each child.',
'He can now form complex sentences and express needs, desires and fears.',
'He is able to jump from a step and land on his feet with complete balance.',
'Start playing "with" other children cooperatively, not just alongside.',
'He can now start leaving the diaper during the day if he shows signs of maturity.',
'He loves to go up and down stairs, alternating his feet without the help of his hands.',
'Your imagination flies: any object can be a plane or a dinosaur.',
'You can now use children\\\\\\\\\\\\\\\'s metal cutlery with complete autonomy.',
'He is able to identify and name most objects in his daily environment.',
'Begin to understand temporal concepts such as "morning", "afternoon" and "night".',
'He can now put on and take off his rubber pants by himself.',
'He loves helping in the kitchen: stirring dough or washing vegetables.',
'His hand-eye coordination allows him to build towers of more than 10 blocks.',
'You can now identify your own feelings and those of others.',
'He begins to show interest in very simple board games (animal lottery).',
'Is able to follow a complex story in a book or short film.',
'You can now pedal a tricycle with strength and direction.',
'He loves to "read" stories by himself, making up the story according to the drawings.',
'His sense of humor is fantastic: he understands jokes and comic situations.',
'He can now wash his teeth, face and hands with minimal help.',
'Begin to understand the concept of "rules" at play and at home.',
'He is able to recognize the letters of his own name in a text.',
'You can now climb complex play structures in the park (with supervision).',
'He is fascinated by exploring nature: collecting stones, leaves and observing insects.',
'His memory capacity allows him to remember what he did at his birthday party.',
'You can now express your opinion about the clothes you want to wear.',
'He begins to show interest in learning songs in other languages.',
'It is able to identify which objects are heavy and which are light.',
'You can now open and close doors with a key (attention to security!).',
'He loves to pretend that he is a superhero or a story character.',
'His coordination allows him to start throwing balls with aim.',
'You can now identify the less visible parts of the body (wrist, ankle).',
'Begin to understand that money is used to buy things (store game).',
'He is able to follow complex three-step instructions in a row.',
'Some children use the potty most of the day; others need more time: follow his pace, without pressure.',
'He is fascinated by seeing how plants grow or how the seasons change.',
'Your vocabulary is enriched with polite words: please, thank you, sorry.',
'It is able to recognize the most common traffic signs close to home.',
'Two years completed! Your son is a unique and wonderful person. Congratulations dads!',
];
